AthenaWorkgroupBucket:
  Type: 'AWS::S3::Bucket'
  Properties:
    AccessControl: Private
    BucketName: !Sub ${Environment}-dap-athena-workgroup
    LoggingConfiguration:
      DestinationBucketName: !Ref GlobalLogBucket
      LogFilePrefix: dap-athena-workgroup/log
    PublicAccessBlockConfiguration:
      BlockPublicAcls: true
      BlockPublicPolicy: true
      IgnorePublicAcls: true
      RestrictPublicBuckets: true
    VersioningConfiguration:
      Status: Enabled
    LifecycleConfiguration:
      Rules:
        - ExpirationInDays: 365
          Status: Enabled
    NotificationConfiguration:
      EventBridgeConfiguration:
        EventBridgeEnabled: true

AthenaWorkgroupBucketPolicy:
  Type: AWS::S3::BucketPolicy
  Properties:
    Bucket: !Ref AthenaWorkgroupBucket
    PolicyDocument:
      Version: 2012-10-17
      Statement:
        - Effect: Deny
          Action: 's3:*'
          Resource: !Sub ${AthenaWorkgroupBucket.Arn}/*
          Principal: '*'
          Condition:
            Bool:
              aws:SecureTransport: false
        - Effect: Allow
          Action:
            - 's3:Get*'
            - 's3:Put*'
            - 's3:List*'
            - 's3:ListBucketMultipartUploads'
            - 's3:AbortMultipartUpload'
            - 's3:ListBucket'
            - 's3:GetBucketLocation'
            - 's3:ListMultipartUploadParts'
          Resource:
            - !Sub ${AthenaWorkgroupBucket.Arn}
            - !Sub ${AthenaWorkgroupBucket.Arn}/*
          Principal:
            AWS: !Sub arn:aws:iam::${AWS::AccountId}:root

AthenaWorkGroup:
  Type: AWS::Athena::WorkGroup
  Properties:
    Name: !Sub ${Environment}-dap-txma-processing
    Description: DAP project
    State: ENABLED
    WorkGroupConfiguration:
      EnforceWorkGroupConfiguration: true
      PublishCloudWatchMetricsEnabled: false
      RequesterPaysEnabled: true
      ResultConfiguration:
        EncryptionConfiguration:
          EncryptionOption: SSE_S3
        OutputLocation: !Sub 's3://${AthenaWorkgroupBucket}/txma/'

AthenaGetConfigLambda:
  # checkov:skip=CKV_AWS_116: DLQ not needed as this lambda failing will cause state machine to fail
  Type: AWS::Serverless::Function
  Properties:
    FunctionName: !Sub athena-get-config-${Environment}
    Handler: athena-get-config.handler
    Architectures:
      - arm64
    Policies:
      - AWSLambdaBasicExecutionRole
      - Statement:
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:ListBucket
            Resource: !Sub arn:aws:s3:::${Environment}-dap-elt-metadata/*
    ReservedConcurrentExecutions: 10
    Environment:
      # checkov:skip=CKV_AWS_173: These environment variables do not require encryption
      Variables:
        ENVIRONMENT: !Ref Environment
    Tags:
      Environment: !Ref Environment
    VpcConfig:
      SecurityGroupIds:
        - !Ref LambdaSecurityGroup
      SubnetIds:
        - !Ref SubnetForDAP1
        - !Ref SubnetForDAP2
        - !Ref SubnetForDAP3

AthenaGetStatementLambda:
  # checkov:skip=CKV_AWS_116: DLQ not needed as this lambda failing will cause state machine to fail
  Type: AWS::Serverless::Function
  Properties:
    FunctionName: !Sub athena-get-statement-${Environment}
    Handler: athena-get-statement.handler
    Architectures:
      - arm64
    Policies:
      - AWSLambdaBasicExecutionRole
      - Statement:
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:ListBucket
            Resource: !Sub arn:aws:s3:::${Environment}-dap-elt-metadata/*
    ReservedConcurrentExecutions: 30
    Environment:
      # checkov:skip=CKV_AWS_173: These environment variables do not require encryption
      Variables:
        ENVIRONMENT: !Ref Environment
    Tags:
      Environment: !Ref Environment
    VpcConfig:
      SecurityGroupIds:
        - !Ref LambdaSecurityGroup
      SubnetIds:
        - !Ref SubnetForDAP1
        - !Ref SubnetForDAP2
        - !Ref SubnetForDAP3
