GlueScriptsExecutionRole:
  Type: AWS::IAM::Role
  Properties:
    RoleName: !Sub ${Environment}-dap-glue-scripts-execution-role-demo
    AssumeRolePolicyDocument:
      Version: 2012-10-17
      Statement:
        - Effect: Allow
          Principal:
            Service:
              - glue.amazonaws.com
          Action:
            - sts:AssumeRole
    Path: /
    Policies:
      - PolicyName: !Sub ${Environment}-dap-glue-scripts-execution-policy--demo
        PolicyDocument:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Resource: arn:aws:s3:::*
              Action:
                - s3:Get*
                - s3:Put*
                - s3:List*
                - s3:ListBucketMultipartUploads
                - s3:AbortMultipartUpload
                - s3:CreateBucket
                - s3:ListBucket
                - s3:GetBucketLocation
                - s3:ListMultipartUploadParts

            - Effect: Allow
              Resource: arn:aws:logs:*:*:*
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
                - logs:CreateLogDelivery
                - logs:GetLogDelivery
                - logs:UpdateLogDelivery
                - logs:DeleteLogDelivery
                - logs:ListLogDeliveries
                - logs:PutResourcePolicy
                - logs:DescribeResourcePolicies
                - logs:DescribeLogGroups
                - logs:AssociateKmsKey

            - Effect: Allow
              Resource: '*'
              Action:
                - athena:GetTableMetadata
                - athena:ListEngineVersions
                - athena:ListDataCatalogs
                - athena:ListDatabases
                - athena:GetDatabase
                - athena:ListTableMetadata
                - athena:ListWorkGroups

            - Effect: Allow
              Resource:
                - !Sub 'arn:aws:athena:${AWS::Region}:${AWS::AccountId}:workgroup/${Environment}-dap-txma-processing'
                - !Sub 'arn:aws:athena:${AWS::Region}:${AWS::AccountId}:workgroup/primary'
                - !Sub 'arn:aws:athena:${AWS::Region}:${AWS::AccountId}:datacatalog/*'
              Action:
                - athena:CreatePreparedStatement
                - athena:StartQueryExecution
                - athena:GetQueryResultsStream
                - athena:UpdatePreparedStatement
                - athena:GetQueryResults
                - athena:DeletePreparedStatement
                - athena:DeleteNamedQuery
                - athena:GetNamedQuery
                - athena:GetPreparedStatement
                - athena:ListQueryExecutions
                - athena:ListNamedQueries
                - athena:GetWorkGroup
                - athena:CreateNamedQuery
                - athena:StopQueryExecution
                - athena:GetQueryExecution
                - athena:BatchGetNamedQuery
                - athena:ListPreparedStatements
                - athena:BatchGetQueryExecution
                - athena:getDataCatalog

            - Effect: Allow
              Resource:
                - !Sub 'arn:aws:glue:${AWS::Region}:${AWS::AccountId}:catalog'
                - !Sub 'arn:aws:glue:${AWS::Region}:${AWS::AccountId}:database/*'
                - !Sub 'arn:aws:glue:${AWS::Region}:${AWS::AccountId}:table/*'
              Action:
                - glue:CreateDatabase
                - glue:GetDatabase
                - glue:GetDatabases
                - glue:UpdateDatabase
                - glue:DeleteDatabase
                - glue:CreateTable
                - glue:UpdateTable
                - glue:GetTable
                - glue:GetTables
                - glue:DeleteTable
                - glue:BatchDeleteTable
                - glue:BatchCreatePartition
                - glue:CreatePartition
                - glue:UpdatePartition
                - glue:GetPartition
                - glue:GetPartitions
                - glue:BatchGetPartition
                - glue:DeletePartition
                - glue:BatchDeletePartition

            - Effect: Allow
              Resource:
                - !Sub 'arn:aws:redshift-serverless:${AWS::Region}:${AWS::AccountId}:workgroup/*'
              Action:
                - redshift-data:BatchExecuteStatement
                - redshift-data:ExecuteStatement
                - redshift-serverless:GetCredentials

            - Effect: Allow
              Resource:
                - '*'
              Action:
                - redshift-data:GetStatementResult
                - redshift-data:DescribeStatement
                - redshift-data:ListStatements

            - Effect: Allow
              Resource:
                - '*'
              Action:
                - kms:*

            - Effect: Allow
              Resource:
                - '*'
              Action:
                - glue:GetConnection

            - Effect: Allow
              Resource:
                - '*'
              Action:
                - ec2:Describe*

            - Effect: Allow
              Resource:
                - '*'
              Action:
                - ec2:CreateNetworkInterface
                - ec2:Describe*
                - ec2:AssignPrivateIpAddresses
                - ec2:UnassignPrivateIpAddresses
                - ec2:CreateTags
                - secretsmanager:GetSecretValue

            - Effect: Allow
              Resource:
                - '*'
              Action:
                - glue:GetSecurityConfiguration

RawStageTransformProcessPythonGlueJob:
  Type: AWS::Glue::Job
  Properties:
    Command:
      Name: pythonshell
      PythonVersion: '3.9'
      ScriptLocation:
        !Join [
          '',
          [s3://demo-dap-githubartifactsourcebucket-qqlbqh8q9cui/, !Ref CommitSha, /raw_to_stage_process_glue_job.py],
        ]
    DefaultArguments:
      '--JOB_NAME': !Sub ${Environment}-dap-raw-stage-transform-process-demo
      '--LOG_LEVEL': 'INFO'
      '--additional-python-modules': 'awswrangler,aws_lambda_powertools'
      '--config_bucket': 'some_bucket'
      '--config_key_path': 'txma/raw_stage_optimisation_solution/configuration_rules/raw_to_stage_config_rules.json'
      '--raw_database': !Sub ${Environment}-txma-raw
      '--raw_source_table': 'txma-refactored'
      '--stage_bucket': some_bucket
      '--stage_database': !Sub ${Environment}-txma-stage
      '--stage_target_table': 'txma_stage_layer'
      '--stage_target_key_value_table': 'txma_stage_layer_key_values'
      '--txma_raw_dedup_view_key_path': 'txma/raw_stage_optimisation_solution/athena_db_object/txma_raw_dedup_view.sql'
      '--workgroup': !Sub ${Environment}-dap-txma-processing
      '--TempDir': s3://some_buckett/raw_stage_optimisation_processing/temporary/
      'library-set': 'analytics'
      '--extra-py-files':
        !Join [
          '',
          [
            s3://demo-dap-githubartifactsourcebucket-qqlbqh8q9cui/,
            !Ref CommitSha,
            /raw_to_stage_etl_modules-0.1.0-py3-none-any.whl,
          ],
        ]
    ExecutionProperty:
      MaxConcurrentRuns: 1
    MaxRetries: 0
    SecurityConfiguration: !Ref GlueSecurityConfig
    MaxCapacity: 1
    Name: !Sub ${Environment}-dap-raw-stage-transform-process-demo
    Role: !Ref GlueScriptsExecutionRole

GlueSecurityConfig:
  Type: AWS::Glue::SecurityConfiguration
  Properties:
    Name: !Sub ${Environment}-dap-glue-security-configuration-demo
    EncryptionConfiguration:
      CloudWatchEncryption:
        CloudWatchEncryptionMode: SSE-KMS
        KmsKeyArn: !GetAtt KmsKey.Arn
      JobBookmarksEncryption:
        JobBookmarksEncryptionMode: CSE-KMS
        KmsKeyArn: !GetAtt KmsKey.Arn
      S3Encryptions:
        - S3EncryptionMode: SSE-KMS
          KmsKeyArn: !GetAtt KmsKey.Arn

KmsKey:
  Type: AWS::KMS::Key
  Properties:
    EnableKeyRotation: true
    KeyPolicy:
      Version: '2012-10-17'
      Statement:
        - Effect: Allow
          Principal:
            AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
          Action: kms:*
          Resource: '*'
        - Effect: Allow
          Principal:
            Service:
              - cloudwatch.amazonaws.com
              - cloudtrail.amazonaws.com
              - lambda.amazonaws.com
              - s3.amazonaws.com
              - sns.amazonaws.com
              - sqs.amazonaws.com
              - logs.amazonaws.com
              - logs.eu-west-2.amazonaws.com
              - glue.amazonaws.com
              - redshift.amazonaws.com
              - redshift-serverless.amazonaws.com
              - chatbot.amazonaws.com
              - events.amazonaws.com
            AWS:
              - !GetAtt GlueScriptsExecutionRole.Arn
          Action:
            - kms:Encrypt*
            - kms:Decrypt*
            - kms:ReEncrypt*
            - kms:GenerateDataKey*
            - kms:Describe*
          Resource: '*'

KmsKeyAlias:
  Type: AWS::KMS::Alias
  Properties:
    AliasName: !Sub alias/${Environment}-dap-key--demo
    TargetKeyId: !Ref KmsKey
