# this queue is the trigger for the EventConsumerLambda in environments
# where there is no connection to a TxMA queue (i.e. dev and build)
# it also exists in production preview to allow manual event injection
EventConsumerQueue:
  Type: AWS::SQS::Queue
  Condition: IsDevOrBuild
  Properties:
    QueueName: !Sub ${Environment}-placeholder-txma-event-queue
    RedrivePolicy:
      deadLetterTargetArn: !GetAtt EventConsumerDlq.Arn
      maxReceiveCount: 1
    KmsMasterKeyId: !GetAtt KmsKey.Arn

EventConsumerDlq:
  Type: AWS::SQS::Queue
  Condition: IsDevOrBuild
  Properties:
    QueueName: !Sub ${Environment}-placeholder-txma-event-dlq
    KmsMasterKeyId: !GetAtt KmsKey.Arn

EventConsumerLambda:
  # checkov:skip=CKV_AWS_116: DLQ not needed for lambda driven by SQS
  # checkov:skip=CKV_AWS_115:Not setting concurrent execution limits,
  Type: AWS::Serverless::Function
  Properties:
    FunctionName: txma-event-consumer
    Handler: txma-event-consumer.handler
    Architectures:
      - arm64
    Policies:
      - AWSLambdaBasicExecutionRole
      - Statement:
          - Effect: Allow
            Action:
              - 'sqs:DeleteMessage'
              - 'sqs:GetQueueAttributes'
              - 'sqs:ReceiveMessage'
            Resource: !If [IsDevOrBuild, !GetAtt EventConsumerQueue.Arn, '{{resolve:ssm:TxMAEventQueueARN}}']
          - Effect: Allow
            Action: firehose:PutRecord
            Resource: !GetAtt KinesisFirehose.Arn
          - Effect: Allow
            Action: firehose:PutRecordBatch
            Resource: !GetAtt KinesisFirehose.Arn
          - Effect: Allow
            Action: kms:decrypt
            Resource: !If [IsDevOrBuild, !GetAtt KmsKey.Arn, '{{resolve:ssm:TxMAKMSKeyARN}}']
    Environment:
      # checkov:skip=CKV_AWS_173: These environment variables do not require encryption
      Variables:
        FIREHOSE_STREAM_NAME: !Sub '${Environment}-${DeliveryStreamName}'
        ENVIRONMENT: !Ref Environment
    Tags:
      Environment: !Ref Environment
    VpcConfig:
      SecurityGroupIds:
        - !Ref LambdaSecurityGroup
      SubnetIds:
        - !Ref SubnetForDAP1
        - !Ref SubnetForDAP2
        - !Ref SubnetForDAP3

EventConsumerEventSourceMapping:
  Type: 'AWS::Lambda::EventSourceMapping'
  Properties:
    BatchSize: 10
    Enabled: true
    ScalingConfig:
      MaximumConcurrency: 300
    EventSourceArn: !If [IsDevOrBuild, !GetAtt EventConsumerQueue.Arn, '{{resolve:ssm:TxMAEventQueueARN}}']
    FunctionName: !GetAtt EventConsumerLambda.Arn
    FunctionResponseTypes:
      - ReportBatchItemFailures

KinesisFirehose:
  Type: 'AWS::KinesisFirehose::DeliveryStream'
  Properties:
    DeliveryStreamName: !Sub ${Environment}-${DeliveryStreamName}
    DeliveryStreamType: DirectPut
    ExtendedS3DestinationConfiguration:
      BucketARN: !GetAtt RawLayerBucket.Arn
      CloudWatchLoggingOptions:
        Enabled: true
        LogGroupName: !Sub ${Environment}-${DeliveryStreamName}
        LogStreamName: !Sub ${Environment}-${DeliveryStreamName}
      BufferingHints:
        IntervalInSeconds: !If [IsDevOrBuild, 60, 900]
        SizeInMBs: 128
      RoleARN: !GetAtt IAMRoleKinesisFirehose.Arn
      Prefix: '!{partitionKeyFromQuery:datasource}-refactored/year=!{partitionKeyFromQuery:year}/month=!{partitionKeyFromQuery:month}/day=!{partitionKeyFromQuery:day}/'
      CompressionFormat: GZIP
      ErrorOutputPrefix: kinesis-processing-errors-
      DynamicPartitioningConfiguration:
        Enabled: true
      ProcessingConfiguration:
        Enabled: true
        Processors:
          - Type: AppendDelimiterToRecord
          - Type: MetadataExtraction
            Parameters:
              - ParameterName: MetadataExtractionQuery
                ParameterValue: '{datasource: "txma",year:now | strftime("%Y"),month:now | strftime("%m"),day:now | strftime("%d")}'
              - ParameterName: JsonParsingEngine
                ParameterValue: 'JQ-1.6'
      DataFormatConversionConfiguration:
        Enabled: false

IAMRoleKinesisFirehose:
  Type: 'AWS::IAM::Role'
  Properties:
    RoleName: !Sub ${Environment}-kinesis-txma-firehose-role
    AssumeRolePolicyDocument:
      Version: 2012-10-17
      Statement:
        - Effect: Allow
          Principal:
            Service: firehose.amazonaws.com
          Action: 'sts:AssumeRole'
    MaxSessionDuration: 3600
    Policies:
      - PolicyName: !Sub ${Environment}-kinesis-txma-firehose-policy
        PolicyDocument:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - 's3:AbortMultipartUpload'
                - 's3:GetBucketLocation'
                - 's3:GetObject'
                - 's3:ListBucket'
                - 's3:ListBucketMultipartUploads'
                - 's3:PutObject'
              Resource:
                - !Sub 'arn:aws:s3:::${RawLayerBucket}'
                - !Sub 'arn:aws:s3:::${RawLayerBucket}/*'
            - Effect: Allow
              Resource: arn:aws:logs:*:*:*
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents

EventConsumerQueueTestUrl:
  Condition: IsDevOrBuild
  Type: AWS::SSM::Parameter
  Properties:
    Name: !Sub /tests/${AWS::StackName}/dapTXMAConsumerSQSQueueUrl
    Type: String
    Value: !GetAtt EventConsumerQueue.QueueUrl

E2ETestProducerQueueKmsKey:
  Type: AWS::KMS::Key
  Condition: IsStaging
  Properties:
    EnableKeyRotation: true
    KeyPolicy:
      Version: '2012-10-17'
      Statement:
        - Sid: Enable root access
          Effect: Allow
          Principal:
            AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
          Action: kms:*
          Resource: '*'
        - Sid: Enable decrypt access for Event Processing
          Effect: Allow
          Principal:
            AWS: '{{resolve:ssm:EventProcessingAccountRootArn}}'
          Action:
            - kms:Decrypt
            - kms:GenerateDataKey
            - kms:DescribeKey
          Resource: '*'
        - Sid: Allow Lambda service access
          Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action:
            - kms:GenerateDataKey
            - kms:Encrypt
            - kms:Decrypt
          Resource: '*'

E2ETestProducerQueueKmsKeyAlias:
  Type: AWS::KMS::Alias
  Condition: IsStaging
  Properties:
    AliasName: !Sub alias/${Environment}-dap-e2e-test-producer-queue-key
    TargetKeyId: !Ref E2ETestProducerQueueKmsKey

E2ETestProducerDeadLetterQueue:
  Type: AWS::SQS::Queue
  Condition: IsStaging
  Properties:
    QueueName: !Sub ${Environment}-dap-e2e-test-producer-dlq
    KmsMasterKeyId: !GetAtt E2ETestProducerQueueKmsKey.Arn

E2ETestProducerQueue:
  Type: AWS::SQS::Queue
  Condition: IsStaging
  Properties:
    QueueName: !Sub ${Environment}-dap-e2e-test-producer-queue
    KmsMasterKeyId: !GetAtt E2ETestProducerQueueKmsKey.Arn
    RedrivePolicy:
      deadLetterTargetArn: !GetAtt E2ETestProducerDeadLetterQueue.Arn
      maxReceiveCount: 5

E2ETestProducerQueuePolicy:
  Type: AWS::SQS::QueuePolicy
  Condition: IsStaging
  Properties:
    Queues:
      - !Ref E2ETestProducerQueue
    PolicyDocument:
      Version: '2012-10-17'
      Statement:
        - Sid: Allow Event Processing account to read from queue
          Effect: Allow
          Principal:
            AWS: '{{resolve:ssm:EventProcessingAccountRootArn}}'
          Action:
            - sqs:ChangeMessageVisibility
            - sqs:ReceiveMessage
            - sqs:DeleteMessage
            - sqs:GetQueueAttributes
            - sqs:GetQueueUrl
          Resource: !GetAtt E2ETestProducerQueue.Arn

E2ETestProducerQueueUrlParameter:
  Type: AWS::SSM::Parameter
  Condition: IsStaging
  Properties:
    Name: !Sub /tests/${AWS::StackName}/dapE2ETestProducerQueueUrl
    Type: String
    Value: !Ref E2ETestProducerQueue

E2ETestObfuscationHmacSecretArnParameter:
  Type: AWS::SSM::Parameter
  Condition: IsStaging
  Properties:
    Name: !Sub /tests/${AWS::StackName}/obfuscationHmacSecretArn
    Type: String
    Value: dap/e2e/ObfuscationHmacKey

E2ETestProducerQueueArnParameter:
  Type: AWS::SSM::Parameter
  Condition: IsStaging
  Properties:
    Name: DAPE2ETestProducerQueueArn
    Type: String
    Value: !GetAtt E2ETestProducerQueue.Arn

E2ETestProducerQueueKmsKeyArnParameter:
  Type: AWS::SSM::Parameter
  Condition: IsStaging
  Properties:
    Name: DAPE2ETestProducerKmsKeyArn
    Type: String
    Value: !GetAtt E2ETestProducerQueueKmsKey.Arn
