RedshiftGetMetadataLambda:
  # checkov:skip=CKV_AWS_116: DLQ not needed as this lambda failing will cause state machine to fail
  Type: AWS::Serverless::Function
  Properties:
    FunctionName: !Sub redshift-get-metadata-${Environment}
    Handler: redshift-get-metadata.handler
    Policies:
      - AWSLambdaBasicExecutionRole
      - Statement:
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:ListBucket
            Resource: !Sub ${ELTMetadataBucket.Arn}/*
    ReservedConcurrentExecutions: 10
    Environment:
      # checkov:skip=CKV_AWS_173: These environment variables do not require encryption
      Variables:
        ENVIRONMENT: !Ref Environment
        METADATA_BUCKET_NAME: !Ref ELTMetadataBucket
    Tags:
      Environment: !Ref Environment
    VpcConfig:
      SecurityGroupIds:
        - !Ref LambdaSecurityGroup
      SubnetIds:
        - !Ref SubnetForDAP1
        - !Ref SubnetForDAP2
        - !Ref SubnetForDAP3

GlueJobResultsBucket:
  Type: 'AWS::S3::Bucket'
  Properties:
    AccessControl: Private
    BucketName: !Sub ${Environment}-dap-glue-job-process-results
    LoggingConfiguration:
      DestinationBucketName: !Ref GlobalLogBucket
      LogFilePrefix: dap-glue-job-process-results/log
    PublicAccessBlockConfiguration:
      BlockPublicAcls: true
      BlockPublicPolicy: true
      IgnorePublicAcls: true
      RestrictPublicBuckets: true
    VersioningConfiguration:
      Status: Enabled
    LifecycleConfiguration:
      Rules:
        - ExpirationInDays: 365
          Status: Enabled
    NotificationConfiguration:
      EventBridgeConfiguration:
        EventBridgeEnabled: true

GlueJobResultsBucketPolicy:
  Type: AWS::S3::BucketPolicy
  Properties:
    Bucket: !Ref GlueJobResultsBucket
    PolicyDocument:
      Version: 2012-10-17
      Statement:
        - Effect: Deny
          Action: 's3:*'
          Resource: !Sub ${GlueJobResultsBucket.Arn}/*
          Principal: '*'
          Condition:
            Bool:
              aws:SecureTransport: false
        - Effect: Allow
          Action:
            - 's3:Get*'
            - 's3:Put*'
            - 's3:List*'
            - 's3:ListBucketMultipartUploads'
            - 's3:AbortMultipartUpload'
            - 's3:ListBucket'
            - 's3:GetBucketLocation'
            - 's3:ListMultipartUploadParts'
          Resource:
            - !Sub ${GlueJobResultsBucket.Arn}
            - !Sub ${GlueJobResultsBucket.Arn}/*
          Principal:
            AWS: !Sub arn:aws:iam::${AWS::AccountId}:root

ReferenceDataSQSQueue:
  Type: AWS::SQS::Queue
  Properties:
    ContentBasedDeduplication: true
    FifoQueue: true
    QueueName: !Sub ${Environment}-dap-reference-data-processing.fifo
    KmsMasterKeyId: !GetAtt KmsKey.Arn
    RedrivePolicy:
      deadLetterTargetArn: !GetAtt DeadLetterQueue.Arn
      maxReceiveCount: 1
    VisibilityTimeout: 120

DeadLetterQueue:
  Type: AWS::SQS::Queue
  Properties:
    FifoQueue: true
    QueueName: !Sub ${Environment}-reference-data-processing-dlq.fifo
    KmsMasterKeyId: !GetAtt KmsKey.Arn

ProcessReferenceDataLogGroup:
  Type: AWS::Logs::LogGroup
  Properties:
    LogGroupName: /aws/stepfunction/dap-reference-data-redshift-ingestion
    KmsKeyId: !GetAtt KmsKey.Arn
    RetentionInDays: 30

ProcessReferenceDataStateMachine:
  Type: AWS::Serverless::StateMachine # More info about State Machine Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-statemachine.html
  Properties:
    DefinitionUri: statemachine/reference_data_processing.asl.json
    Name: !Sub ${Environment}-dap-reference-data-redshift-ingestion
    Role: !GetAtt StepFunctionRole.Arn
    Logging:
      Destinations:
        - CloudWatchLogsLogGroup:
            LogGroupArn: !GetAtt ProcessReferenceDataLogGroup.Arn
      IncludeExecutionData: true
      Level: ALL
    DefinitionSubstitutions:
      ReferenceDataIngestionGlueJobName: !Ref ReferenceDataRedshiftIngestionGlueJob
      GetRedshiftMetadataFunctionArn: !GetAtt RedshiftGetMetadataLambda.Arn

ReferenceDataProcessingPipeRole:
  Type: 'AWS::IAM::Role'
  Properties:
    AssumeRolePolicyDocument:
      Version: '2012-10-17'
      Statement:
        - Effect: 'Allow'
          Principal:
            Service: 'pipes.amazonaws.com'
          Action: 'sts:AssumeRole'
    Policies:
      - PolicyName: 'BaseInlinePolicy'
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Sid: 'AccessToCloudWatch'
              Effect: 'Allow'
              Action:
                - 'logs:CreateLogGroup'
                - 'logs:CreateLogStream'
                - 'logs:PutLogEvents'
              Resource: arn:aws:logs:*:*:*
            - Sid: 'UseSqsAsSource'
              Effect: 'Allow'
              Action:
                - 'sqs:ReceiveMessage'
                - 'sqs:DeleteMessage'
                - 'sqs:GetQueueAttributes'
              Resource: !GetAtt 'ReferenceDataSQSQueue.Arn'
            - Sid: 'ExecuteSfnWorkflowAsTarget'
              Effect: 'Allow'
              Action:
                - 'states:StartSyncExecution'
                - 'states:StartExecution'
                - 'states:ListExecutions'
              Resource: !Ref 'ProcessReferenceDataStateMachine'
            - Effect: Allow
              Action:
                - kms:Decrypt
                - kms:Encrypt
                - kms:DescribeKey
                - kms:GenerateDataKey
              Resource: !GetAtt KmsKey.Arn

ReferenceDataProcessingPipe:
  Type: 'AWS::Pipes::Pipe'
  Properties:
    RoleArn: !GetAtt 'ReferenceDataProcessingPipeRole.Arn'
    Source: !GetAtt 'ReferenceDataSQSQueue.Arn'
    SourceParameters:
      SqsQueueParameters:
        BatchSize: 1
    Target: !Ref 'ProcessReferenceDataStateMachine'
    TargetParameters:
      StepFunctionStateMachineParameters:
        InvocationType: 'FIRE_AND_FORGET'

GlueRedshiftConnection:
  Type: AWS::Glue::Connection
  Properties:
    CatalogId: !Ref AWS::AccountId
    ConnectionInput:
      Name: !Sub ${Environment}-redshift-connection
      ConnectionType: 'JDBC'
      ConnectionProperties:
        JDBC_CONNECTION_URL: !Sub 'jdbc:redshift://${Environment}-redshift-serverless-workgroup.${AWS::AccountId}.${AWS::Region}.redshift-serverless.amazonaws.com:5439/dap_txma_reporting_db'
        SECRET_ID: !Ref RedshiftSecret
      PhysicalConnectionRequirements:
        SecurityGroupIdList:
          - !GetAtt VPCForDAP.DefaultSecurityGroup
        SubnetId: !Ref SubnetForDAP3

ReferenceDataRedshiftIngestionGlueJob:
  Type: AWS::Glue::Job
  Properties:
    Command:
      Name: 'glueetl'
      ScriptLocation: !Sub s3://${ELTMetadataBucket}/reference_data/manual_curated_dataset_ingestion/scripts/reference_data_redshift_ingestion_script.py
    GlueVersion: '4.0'
    NumberOfWorkers: 2
    WorkerType: 'G.1X'
    Connections:
      Connections:
        - !Ref GlueRedshiftConnection
    DefaultArguments:
      '--JOB_NAME': !Sub ${Environment}-reference-data-redshift-ingestion-job
      '--TempDir': !Sub s3://${GlueJobResultsBucket}/temporary/
      '--RedshiftTempDir': !Sub s3://${GlueJobResultsBucket}/redshift/temporary/
      '--GlueConnection': !Ref GlueRedshiftConnection
    ExecutionProperty:
      MaxConcurrentRuns: 10
    MaxRetries: 0
    SecurityConfiguration: !Ref GlueSecurityConfig
    Name: !Sub ${Environment}-reference-data-redshift-ingestion-job
    Role: !Ref GlueScriptsExecutionRole

S3SendMetadataLambda:
  # checkov:skip=CKV_AWS_116: DLQ not needed as this lambda failing will cause state machine to fail
  Type: AWS::Serverless::Function
  Properties:
    FunctionName: !Sub s3-send-metadata-${Environment}
    Handler: s3-send-metadata.handler
    Policies:
      - AWSLambdaBasicExecutionRole
      - Statement:
          - Effect: Allow
            Action: sqs:SendMessage
            Resource: !GetAtt ReferenceDataSQSQueue.Arn
          - Effect: Allow
            Action:
              - kms:Decrypt
              - kms:GenerateDataKey*
              - kms:Encrypt
            Resource: !GetAtt KmsKey.Arn
    ReservedConcurrentExecutions: 10
    Environment:
      # checkov:skip=CKV_AWS_173: These environment variables do not require encryption
      Variables:
        ENVIRONMENT: !Ref Environment
        METADATA_QUEUE_URL: !Ref ReferenceDataSQSQueue
    Tags:
      Environment: !Ref Environment
    VpcConfig:
      SecurityGroupIds:
        - !Ref LambdaSecurityGroup
      SubnetIds:
        - !Ref SubnetForDAP1
        - !Ref SubnetForDAP2
        - !Ref SubnetForDAP3

S3SendMetadataLambdaPermission:
  Type: AWS::Lambda::Permission
  Properties:
    FunctionName: !Ref S3SendMetadataLambda
    Action: lambda:InvokeFunction
    Principal: s3.amazonaws.com
    SourceAccount: !Sub ${AWS::AccountId}
    SourceArn: !Sub arn:aws:s3:::${Environment}-dap-stage-layer
