TxmaStepFunctionFailureAlarm:
  Type: AWS::CloudWatch::Alarm
  Properties:
    AlarmName: !Sub '${Environment}-${AWS::StackName}-raw-to-adm-step-failed'
    AlarmDescription: !Sub 'Alarm for ${Environment}-${AWS::StackName}-txma-raw-consolidated-schema-to-stage-process step function execution failures'
    MetricName: ExecutionsFailed
    Namespace: AWS/States
    Statistic: Sum
    Period: 600
    EvaluationPeriods: 1
    Threshold: 1
    ComparisonOperator: GreaterThanOrEqualToThreshold
    Dimensions:
      - Name: StateMachineArn
        Value: !Ref TxmaRawLayerConsolidatedSchemaProcessingStateMachine
    AlarmActions:
      - !Ref DAPNotificationsTopic

TxmaStepFunctionAbortedAlarm:
  Type: AWS::CloudWatch::Alarm
  Properties:
    AlarmName: !Sub '${Environment}-${AWS::StackName}-raw-to-adm-step-aborted'
    AlarmDescription: !Sub 'Alarm for ${Environment}-${AWS::StackName}-txma-raw-consolidated-schema-to-stage-process step function execution aborts'
    MetricName: ExecutionsAborted
    Namespace: AWS/States
    Statistic: Sum
    Period: 600
    EvaluationPeriods: 1
    Threshold: 1
    ComparisonOperator: GreaterThanOrEqualToThreshold
    Dimensions:
      - Name: StateMachineArn
        Value: !Ref TxmaRawLayerConsolidatedSchemaProcessingStateMachine
    AlarmActions:
      - !Ref DAPNotificationsTopic

TxmaStepFunctionLongRunningAlarm:
  Type: 'AWS::CloudWatch::Alarm'
  Properties:
    AlarmName: !Sub '${Environment}-${AWS::StackName}-raw-to-adm-long-running'
    AlarmDescription: !Sub 'Alarm for long-running ${Environment}-${AWS::StackName}-txma-raw-consolidated-schema-to-stage-process step function executions'
    MetricName: ExecutionTime
    Namespace: AWS/States
    Statistic: Maximum
    Period: 600
    EvaluationPeriods: 1
    Threshold: 14400000
    ComparisonOperator: GreaterThanThreshold
    Dimensions:
      - Name: StateMachineArn
        Value: !Ref TxmaRawLayerConsolidatedSchemaProcessingStateMachine
    AlarmActions:
      - !Ref DAPNotificationsTopic

RedshiftProcessingStepFunctionRetryAlarm:
  Type: 'AWS::CloudWatch::Alarm'
  Properties:
    AlarmName: !Sub '${Environment}-${AWS::StackName}-redshift-retry'
    AlarmDescription: !Sub '${Environment}-${AWS::StackName}-consolidated-stage-layer-to-redshift-processing step function is being retried'
    MetricName: ExecutionsFailed
    Namespace: AWS/States
    Statistic: Sum
    Period: 300
    EvaluationPeriods: 1
    Threshold: 1
    ComparisonOperator: GreaterThanOrEqualToThreshold
    Dimensions:
      - Name: StateMachineArn
        Value: !Ref RedshiftConsolidatedModelProcessingStateMachine
    TreatMissingData: notBreaching
    AlarmActions:
      - !Ref DAPNotificationsTopic

ADMProcessingStepFunctionRetryAlarm:
  Type: 'AWS::CloudWatch::Alarm'
  Condition: IsADMEnvironment
  Properties:
    AlarmName: !Sub '${Environment}-${AWS::StackName}-adm-retry'
    AlarmDescription: !Sub '${Environment}-${AWS::StackName}-consolidated-conformed-layer-to-adm-processing step function is being retried'
    MetricName: ExecutionsFailed
    Namespace: AWS/States
    Statistic: Sum
    Period: 300
    EvaluationPeriods: 1
    Threshold: 1
    ComparisonOperator: GreaterThanOrEqualToThreshold
    Dimensions:
      - Name: StateMachineArn
        Value: !Ref ADMConsolidatedModelProcessingStateMachine
    TreatMissingData: notBreaching
    AlarmActions:
      - !Ref DAPNotificationsTopic
