TxmaRawToADMStepFunctionFailureAlarm:
  Type: 'AWS::CloudWatch::Alarm'
  Properties:
    AlarmName: !Sub '${AWS::StackName}-raw-to-adm-step-failed'
    AlarmDescription: 'Alarm for TxMA Raw to ADM Step Function execution failures'
    MetricName: ExecutionsFailed
    Namespace: AWS/States
    Statistic: Sum
    Period: 900
    EvaluationPeriods: 1
    Threshold: 1
    ComparisonOperator: GreaterThanOrEqualToThreshold
    Dimensions:
      - Name: StateMachineArn
        Value: !Ref TxmaRawLayerConsolidatedSchemaProcessingStateMachine
    AlarmActions:
      - !Ref SNSReferenceDataAlertTopic

TxmaStepFunctionAbortedAlarm:
  Type: 'AWS::CloudWatch::Alarm'
  Properties:
    AlarmName: !Sub '${AWS::StackName}-raw-to-adm-step-aborted'
    AlarmDescription: 'Alarm for TxMA Step Function execution aborts'
    MetricName: ExecutionsAborted
    Namespace: AWS/States
    Statistic: Sum
    Period: 900
    EvaluationPeriods: 1
    Threshold: 1
    ComparisonOperator: GreaterThanOrEqualToThreshold
    Dimensions:
      - Name: StateMachineArn
        Value: !Ref TxmaRawLayerConsolidatedSchemaProcessingStateMachine
    AlarmActions:
      - !Ref SNSReferenceDataAlertTopic

TxmaStepFunctionLongRunningAlarm:
  Type: 'AWS::CloudWatch::Alarm'
  Properties:
    AlarmName: !Sub '${AWS::StackName}-raw-to-adm-long-running'
    AlarmDescription: 'Alarm for long-running TxMA Step Function executions'
    MetricName: ExecutionTime
    Namespace: AWS/States
    Statistic: Maximum
    Period: 900
    EvaluationPeriods: 1
    Threshold: 14400000
    ComparisonOperator: GreaterThanThreshold
    Dimensions:
      - Name: StateMachineArn
        Value: !Ref TxmaRawLayerConsolidatedSchemaProcessingStateMachine
    AlarmActions:
      - !Ref SNSReferenceDataAlertTopic
