TxmaStepFunctionFailureAlarm:
  Type: AWS::CloudWatch::Alarm
  Properties:
    AlarmName: !Sub '${Environment}-${AWS::StackName}-raw-to-adm-step-failed'
    AlarmDescription: !Sub 'Alarm for ${Environment}-${AWS::StackName}-txma-raw-consolidated-schema-to-stage-process step function execution failures'
    MetricName: ExecutionsFailed
    Namespace: AWS/States
    Statistic: Sum
    Period: 600
    EvaluationPeriods: 1
    Threshold: 1
    ComparisonOperator: GreaterThanOrEqualToThreshold
    Dimensions:
      - Name: StateMachineArn
        Value: !Ref TxmaRawLayerConsolidatedSchemaProcessingStateMachine
    AlarmActions:
      - !Ref DAPNotificationsTopic

TxmaStepFunctionAbortedAlarm:
  Type: AWS::CloudWatch::Alarm
  Properties:
    AlarmName: !Sub '${Environment}-${AWS::StackName}-raw-to-adm-step-aborted'
    AlarmDescription: !Sub 'Alarm for ${Environment}-${AWS::StackName}-txma-raw-consolidated-schema-to-stage-process step function execution aborts'
    MetricName: ExecutionsAborted
    Namespace: AWS/States
    Statistic: Sum
    Period: 600
    EvaluationPeriods: 1
    Threshold: 1
    ComparisonOperator: GreaterThanOrEqualToThreshold
    Dimensions:
      - Name: StateMachineArn
        Value: !Ref TxmaRawLayerConsolidatedSchemaProcessingStateMachine
    AlarmActions:
      - !Ref DAPNotificationsTopic

TxmaStepFunctionLongRunningAlarm:
  Type: 'AWS::CloudWatch::Alarm'
  Properties:
    AlarmName: !Sub '${Environment}-${AWS::StackName}-raw-to-adm-long-running'
    AlarmDescription: !Sub 'Alarm for long-running ${Environment}-${AWS::StackName}-txma-raw-consolidated-schema-to-stage-process step function executions'
    MetricName: ExecutionTime
    Namespace: AWS/States
    Statistic: Maximum
    Period: 600
    EvaluationPeriods: 1
    Threshold: 14400000
    ComparisonOperator: GreaterThanThreshold
    Dimensions:
      - Name: StateMachineArn
        Value: !Ref TxmaRawLayerConsolidatedSchemaProcessingStateMachine
    AlarmActions:
      - !Ref DAPNotificationsTopic

RedshiftProcessingStepFunctionRetryMinAlarm:
  Type: 'AWS::CloudWatch::Alarm'
  Properties:
    AlarmName: !Sub '${Environment}-${AWS::StackName}-redshift-retry-min'
    AlarmDescription: !Sub 'Minimum threshold for retry detection of ${Environment}-${AWS::StackName}-consolidated-stage-layer-to-redshift-processing step function'
    MetricName: ExecutionsFailed
    Namespace: AWS/States
    Statistic: Sum
    Period: 300
    EvaluationPeriods: 1
    Threshold: 1
    ComparisonOperator: GreaterThanOrEqualToThreshold
    Dimensions:
      - Name: StateMachineArn
        Value: !Ref RedshiftConsolidatedModelProcessingStateMachine
    TreatMissingData: notBreaching

RedshiftProcessingStepFunctionRetryMaxAlarm:
  Type: 'AWS::CloudWatch::Alarm'
  Properties:
    AlarmName: !Sub '${Environment}-${AWS::StackName}-redshift-retry-max'
    AlarmDescription: !Sub 'Maximum threshold for retry detection of ${Environment}-${AWS::StackName}-consolidated-stage-layer-to-redshift-processing step function'
    MetricName: ExecutionsFailed
    Namespace: AWS/States
    Statistic: Sum
    Period: 300
    EvaluationPeriods: 1
    Threshold: 3
    ComparisonOperator: LessThanThreshold
    Dimensions:
      - Name: StateMachineArn
        Value: !Ref RedshiftConsolidatedModelProcessingStateMachine
    TreatMissingData: notBreaching

RedshiftProcessingStepFunctionRetryAlarm:
  Type: 'AWS::CloudWatch::CompositeAlarm'
  Properties:
    AlarmName: !Sub '${Environment}-${AWS::StackName}-redshift-processing-retry'
    AlarmDescription: !Sub 'Alarm when ${Environment}-${AWS::StackName}-consolidated-stage-layer-to-redshift-processing is retried (1-2 failures only)'
    AlarmRule: !Sub 'ALARM(${RedshiftProcessingStepFunctionRetryMinAlarm}) AND ALARM(${RedshiftProcessingStepFunctionRetryMaxAlarm})'
    AlarmActions:
      - !Ref DAPNotificationsTopic

ADMProcessingStepFunctionRetryMinAlarm:
  Type: 'AWS::CloudWatch::Alarm'
  Condition: IsADMEnvironment
  Properties:
    AlarmName: !Sub '${Environment}-${AWS::StackName}-adm-retry-min'
    AlarmDescription: !Sub 'Minimum threshold for ADM retry detection for ${Environment}-${AWS::StackName}-consolidated-conformed-layer-to-adm-processing step function'
    MetricName: ExecutionsFailed
    Namespace: AWS/States
    Statistic: Sum
    Period: 300
    EvaluationPeriods: 1
    Threshold: 1
    ComparisonOperator: GreaterThanOrEqualToThreshold
    Dimensions:
      - Name: StateMachineArn
        Value: !Ref ADMConsolidatedModelProcessingStateMachine
    TreatMissingData: notBreaching

ADMProcessingStepFunctionRetryMaxAlarm:
  Type: 'AWS::CloudWatch::Alarm'
  Condition: IsADMEnvironment
  Properties:
    AlarmName: !Sub '${Environment}-${AWS::StackName}-adm-retry-max'
    AlarmDescription: !Sub 'Maximum threshold for ADM retry detection for ${Environment}-${AWS::StackName}-consolidated-conformed-layer-to-adm-processing step function'
    MetricName: ExecutionsFailed
    Namespace: AWS/States
    Statistic: Sum
    Period: 300
    EvaluationPeriods: 1
    Threshold: 3
    ComparisonOperator: LessThanThreshold
    Dimensions:
      - Name: StateMachineArn
        Value: !Ref ADMConsolidatedModelProcessingStateMachine
    TreatMissingData: notBreaching

ADMProcessingStepFunctionRetryAlarm:
  Type: 'AWS::CloudWatch::CompositeAlarm'
  Condition: IsADMEnvironment
  Properties:
    AlarmName: !Sub '${Environment}-${AWS::StackName}-adm-processing-retry'
    AlarmDescription: !Sub 'Alarm when ${Environment}-${AWS::StackName}-consolidated-conformed-layer-to-adm-processing step function is retried (1-2 failures only)'
    AlarmRule: !Sub 'ALARM(${ADMProcessingStepFunctionRetryMinAlarm}) AND ALARM(${ADMProcessingStepFunctionRetryMaxAlarm})'
    AlarmActions:
      - !Ref DAPNotificationsTopic
