SustainabilityAccountIds:
  #checkov:skip=CKV_AWS_149:We will use aws managed kms key
  Type: AWS::SecretsManager::Secret
  DeletionPolicy: Retain
  UpdateReplacePolicy: Retain
  Condition: IsADMEnvironment
  Properties:
    Description: 'a secret to store account id for SRE account'
    Name: cur-account-ids
    SecretString: '{"ct-shared-services":"xxx", "source-bill-payer": "xxx"}'
