TXMAEventConsumerFunctionFirehoseErrorMetricFilter:
  Type: AWS::Logs::MetricFilter
  Properties:
    LogGroupName: '/aws/lambda/txma-event-consumer'
    FilterPattern: '{ $.message = "Error delivering data" }'
    MetricTransformations:
      - MetricValue: '1'
        MetricNamespace: DAP/TXMAEventConsumer/Logs
        MetricName: !Sub ${Environment}-txma-event-consumer-firehose-error

TXMAEventConsumerFunctionValidationFilter:
  Type: AWS::Logs::MetricFilter
  Properties:
    LogGroupName: '/aws/lambda/txma-event-consumer'
    FilterPattern: '{ $.message = "Invalid audit event" }'
    MetricTransformations:
      - MetricValue: '1'
        MetricNamespace: DAP/TXMAEventConsumer/Logs
        MetricName: !Sub ${Environment}-txma-event-consumer-validation-error

TXMAEventConsumerFunctionFirehoseErrorAlarm:
  Type: AWS::CloudWatch::Alarm
  Properties:
    AlarmActions:
      - !Ref DAPNotificationsTopic
    AlarmDescription: >-
      Alarm that triggers when DAP Firehose delivery errors occur
    AlarmName: !Sub '${Environment}-txma-event-consumer-firehose-alarm'
    ComparisonOperator: GreaterThanThreshold
    DatapointsToAlarm: 1
    EvaluationPeriods: 1
    Threshold: 0
    MetricName: !Sub ${Environment}-txma-event-consumer-firehose-error
    Namespace: DAP/TXMAEventConsumer/Logs
    Statistic: Sum
    Period: 60

TXMAEventConsumerFunctionValidationErrorAlarm:
  Type: AWS::CloudWatch::Alarm
  Properties:
    AlarmActions:
      - !Ref DAPNotificationsTopic
    AlarmDescription: >-
      Alarm that triggers when DAP receives an event that fails validation
    AlarmName: !Sub '${Environment}-txma-event-consumer-validation-alarm'
    ComparisonOperator: GreaterThanThreshold
    DatapointsToAlarm: 1
    EvaluationPeriods: 1
    Threshold: 0
    MetricName: !Sub ${Environment}-txma-event-consumer-validation-error
    Namespace: DAP/TXMAEventConsumer/Logs
    Statistic: Sum
    Period: 60

TXMAEventConsumerFunctionDurationAlarm:
  Type: AWS::CloudWatch::Alarm
  Properties:
    AlarmActions:
      - !Ref DAPNotificationsTopic
    AlarmDescription: >
      Alarm that triggers when DAPs Event Consumer Lambda runs longer than 3 minutes
    AlarmName: !Sub '${AWS::StackName}-txma-event-consumer-duration-alarm'
    ComparisonOperator: GreaterThanThreshold
    DatapointsToAlarm: 1
    EvaluationPeriods: 1
    Threshold: 180000
    MetricName: Duration
    Namespace: DAP/TXMAEventConsumer/Logs
    Statistic: Maximum
    Period: 60
    Dimensions:
      - Name: FunctionName
        Value: !Sub '${Environment}-txma-event-consumer'

GlueStageLayerTableMissingMetricFilter:
  Type: AWS::Logs::MetricFilter
  Properties:
    LogGroupName: !Sub /aws-glue/python-jobs/${Environment}-dap-glue-security-configuration-role/${Environment}-dap-glue-scripts-execution-role/output
    FilterPattern: '{ $.message = "Error querying glue data catalog" }'
    MetricTransformations:
      - MetricNamespace: DAP/RawToStage/Logs
        MetricName: !Sub ${Environment}-raw-to-stage-etl-stage-layer-missing-error
        MetricValue: '1'
        DefaultValue: 0

GlueStageLayerTableMissingAlarm:
  Type: AWS::CloudWatch::Alarm
  Properties:
    AlarmName: !Sub ${Environment}-raw-to-stage-etl-stage-layer-missing-alarm
    AlarmDescription: Alarm when any error from ETL job is logged
    MetricName: !Sub ${Environment}-raw-to-stage-etl-stage-layer-missing-error
    Namespace: DAP/RawToStage/Logs
    Statistic: Sum
    Period: 300
    EvaluationPeriods: 1
    Threshold: 1
    ComparisonOperator: GreaterThanOrEqualToThreshold
    AlarmActions:
      - !Ref DAPNotificationsTopic
    TreatMissingData: notBreaching

GlueRawLayerQueryErrorMetricFilter:
  Type: AWS::Logs::MetricFilter
  Properties:
    LogGroupName: !Sub /aws-glue/python-jobs/${Environment}-dap-glue-security-configuration-role/${Environment}-dap-glue-scripts-execution-role/output
    FilterPattern: '{ $.message = "Error reading Athena table" }'
    MetricTransformations:
      - MetricNamespace: DAP/RawToStage/Logs
        MetricName: !Sub ${Environment}-raw-to-stage-etl-raw-layer-query-error
        MetricValue: '1'
        DefaultValue: 0

GlueRawLayerQueryErrorAlarm:
  Type: AWS::CloudWatch::Alarm
  Properties:
    AlarmName: !Sub ${Environment}-raw-to-stage-etl-raw-layer-query-alarm
    AlarmDescription: Alarm when any error from ETL job is logged
    MetricName: !Sub ${Environment}-raw-to-stage-etl-raw-layer-query-error
    Namespace: DAP/RawToStage/Logs
    Statistic: Sum
    Period: 300
    EvaluationPeriods: 1
    Threshold: 1
    ComparisonOperator: GreaterThanOrEqualToThreshold
    AlarmActions:
      - !Ref DAPNotificationsTopic
    TreatMissingData: notBreaching

GlueStageLayerInsertErrorMetricFilter:
  Type: AWS::Logs::MetricFilter
  Properties:
    LogGroupName: !Sub /aws-glue/python-jobs/${Environment}-dap-glue-security-configuration-role/${Environment}-dap-glue-scripts-execution-role/output
    FilterPattern: '{ $.message = "Error writing to Athena table" }'
    MetricTransformations:
      - MetricNamespace: DAP/RawToStage/Logs
        MetricName: !Sub ${Environment}-raw-to-stage-etl-stage-layer-insert-error
        MetricValue: '1'
        DefaultValue: 0

GlueStageLayerInsertErrorAlarm:
  Type: AWS::CloudWatch::Alarm
  Properties:
    AlarmName: !Sub ${Environment}-raw-to-stage-etl-stage-layer-insert-alarm
    AlarmDescription: Alarm when any error from ETL job is logged
    MetricName: !Sub ${Environment}-raw-to-stage-etl-stage-layer-insert-error
    Namespace: DAP/RawToStage/Logs
    Statistic: Sum
    Period: 300
    EvaluationPeriods: 1
    Threshold: 1
    ComparisonOperator: GreaterThanOrEqualToThreshold
    AlarmActions:
      - !Ref DAPNotificationsTopic
    TreatMissingData: notBreaching

GlueReadConfigErrorMetricFilter:
  Type: AWS::Logs::MetricFilter
  Properties:
    LogGroupName: !Sub /aws-glue/python-jobs/${Environment}-dap-glue-security-configuration-role/${Environment}-dap-glue-scripts-execution-role/output
    FilterPattern: '{ $.message = "Error reading JSON from S3" }'
    MetricTransformations:
      - MetricNamespace: DAP/RawToStage/Logs
        MetricName: !Sub ${Environment}-raw-to-stage-etl-s3-read-config-error
        MetricValue: '1'
        DefaultValue: 0

GlueReadConfigErrorAlarm:
  Type: AWS::CloudWatch::Alarm
  Properties:
    AlarmName: !Sub ${Environment}-raw-to-stage-etl-s3-read-config-alarm
    AlarmDescription: Alarm when any error from ETL job is logged
    MetricName: !Sub ${Environment}-raw-to-stage-etl-s3-read-config-error
    Namespace: DAP/RawToStage/Logs
    Statistic: Sum
    Period: 300
    EvaluationPeriods: 1
    Threshold: 1
    ComparisonOperator: GreaterThanOrEqualToThreshold
    AlarmActions:
      - !Ref DAPNotificationsTopic
    TreatMissingData: notBreaching

GlueWriteToS3ErrorMetricFilter:
  Type: AWS::Logs::MetricFilter
  Properties:
    LogGroupName: !Sub /aws-glue/python-jobs/${Environment}-dap-glue-security-configuration-role/${Environment}-dap-glue-scripts-execution-role/output
    FilterPattern: '{ $.message = "Error writing JSON to S3:" }'
    MetricTransformations:
      - MetricNamespace: DAP/RawToStage/Logs
        MetricName: !Sub ${Environment}-raw-to-stage-etl-s3-write-error
        MetricValue: '1'
        DefaultValue: 0

GlueWriteToS3ErrorAlarm:
  Type: AWS::CloudWatch::Alarm
  Properties:
    AlarmName: !Sub ${Environment}-raw-to-stage-etl-s3-write-alarm
    AlarmDescription: Alarm when any error from ETL job is logged
    MetricName: !Sub ${Environment}-raw-to-stage-etl-s3-write-error
    Namespace: DAP/RawToStage/Logs
    Statistic: Sum
    Period: 300
    EvaluationPeriods: 1
    Threshold: 1
    ComparisonOperator: GreaterThanOrEqualToThreshold
    AlarmActions:
      - !Ref DAPNotificationsTopic
    TreatMissingData: notBreaching

GlueReadFileFromS3ErrorMetricFilter:
  Type: AWS::Logs::MetricFilter
  Properties:
    LogGroupName: !Sub /aws-glue/python-jobs/${Environment}-dap-glue-security-configuration-role/${Environment}-dap-glue-scripts-execution-role/output
    FilterPattern: '{ $.message = "Error reading file from S3" }'
    MetricTransformations:
      - MetricNamespace: DAP/RawToStage/Logs
        MetricName: !Sub ${Environment}-raw-to-stage-etl-s3-read-file-error
        MetricValue: '1'
        DefaultValue: 0

GlueReadFileFromS3ErrorAlarm:
  Type: AWS::CloudWatch::Alarm
  Properties:
    AlarmName: !Sub ${Environment}-raw-to-stage-etl-s3-read-file-alarm
    AlarmDescription: Alarm when any error from ETL job is logged
    MetricName: !Sub ${Environment}-raw-to-stage-etl-s3-read-file-error
    Namespace: DAP/RawToStage/Logs
    Statistic: Sum
    Period: 300
    EvaluationPeriods: 1
    Threshold: 1
    ComparisonOperator: GreaterThanOrEqualToThreshold
    AlarmActions:
      - !Ref DAPNotificationsTopic
    TreatMissingData: notBreaching

GlueStageLayerGenericInsertErrorMetricFilter:
  Type: AWS::Logs::MetricFilter
  Properties:
    LogGroupName: !Sub /aws-glue/python-jobs/${Environment}-dap-glue-security-configuration-role/${Environment}-dap-glue-scripts-execution-role/output
    FilterPattern: '{ $.message = "Exception Error writing to Stage layer" }'
    MetricTransformations:
      - MetricNamespace: DAP/RawToStage/Logs
        MetricName: !Sub ${Environment}-raw-to-stage-etl-stage-layer-generic-insert-error
        MetricValue: '1'
        DefaultValue: 0

GlueStageLayerGenericInsertErrorAlarm:
  Type: AWS::CloudWatch::Alarm
  Properties:
    AlarmName: !Sub ${Environment}-raw-to-stage-etl-stage-layer-generic-insert-alarm
    AlarmDescription: Alarm when any error from ETL job is logged
    MetricName: !Sub ${Environment}-raw-to-stage-etl-stage-layer-generic-insert-error
    Namespace: DAP/RawToStage/Logs
    Statistic: Sum
    Period: 300
    EvaluationPeriods: 1
    Threshold: 1
    ComparisonOperator: GreaterThanOrEqualToThreshold
    AlarmActions:
      - !Ref DAPNotificationsTopic
    TreatMissingData: notBreaching

GenericValueExceptionErrorMetricFilter:
  Type: AWS::Logs::MetricFilter
  Properties:
    LogGroupName: !Sub /aws-glue/python-jobs/${Environment}-dap-glue-security-configuration-role/${Environment}-dap-glue-scripts-execution-role/output
    FilterPattern: '{ $.message = "Value Error: *" }'
    MetricTransformations:
      - MetricNamespace: DAP/RawToStage/Logs
        MetricName: !Sub ${Environment}-raw-to-stage-etl-value-exception-error
        MetricValue: '1'
        DefaultValue: 0

GenericValueExceptionErrorAlarm:
  Type: AWS::CloudWatch::Alarm
  Properties:
    AlarmName: !Sub ${Environment}-raw-to-stage-etl-value-exception-alarm
    AlarmDescription: Alarm when any error from ETL job is logged
    MetricName: !Sub ${Environment}-raw-to-stage-etl-value-exception-error
    Namespace: DAP/RawToStage/Logs
    Statistic: Sum
    Period: 300
    EvaluationPeriods: 1
    Threshold: 1
    ComparisonOperator: GreaterThanOrEqualToThreshold
    AlarmActions:
      - !Ref DAPNotificationsTopic
    TreatMissingData: notBreaching

GenericExceptionErrorMetricFilter:
  Type: AWS::Logs::MetricFilter
  Properties:
    LogGroupName: !Sub /aws-glue/python-jobs/${Environment}-dap-glue-security-configuration-role/${Environment}-dap-glue-scripts-execution-role/output
    FilterPattern: '{ $.message = "Exception Error: *" }'
    MetricTransformations:
      - MetricNamespace: DAP/RawToStage/Logs
        MetricName: !Sub ${Environment}-raw-to-stage-etl-generic-exception-error
        MetricValue: '1'
        DefaultValue: 0

GenericExceptionErrorAlarm:
  Type: AWS::CloudWatch::Alarm
  Properties:
    AlarmName: !Sub ${Environment}-raw-to-stage-etl-generic-exception-alarm
    AlarmDescription: Alarm when any error from ETL job is logged
    MetricName: !Sub ${Environment}-raw-to-stage-etl-generic-exception-error
    Namespace: DAP/RawToStage/Logs
    Statistic: Sum
    Period: 300
    EvaluationPeriods: 1
    Threshold: 1
    ComparisonOperator: GreaterThanOrEqualToThreshold
    AlarmActions:
      - !Ref DAPNotificationsTopic
    TreatMissingData: notBreaching
