AWSTemplateFormatVersion: 2010-09-09
Description: Data and Analytics Stack
Transform: AWS::Serverless-2016-10-31

Outputs:
  TXMAQueueURL:
    Description: 'TxMA queue URL'
    Value: !If [UsePlaceholderTxMAQueue, !Ref EventConsumerQueue, '']

  TXMABucket:
    Description: 'Name of raw bucket'
    Value: !Ref RawLayerBucket

Parameters:
  Environment:
    Description: Environment type
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - test
      - feature
      - build
      - staging
      - integration
      - production
      - production-preview
  CodeSigningConfigArn:
    Description: ARN of Code Signing Config from deployment pipeline
    Type: String
    Default: none
  PermissionsBoundary:
    Description: ARN of permissions boundary for new roles
    Type: String
    Default: none
  DeliveryStreamName:
    Description: Kinesis Firehose delivery stream name
    Type: String
    Default: dap-txma-delivery-stream
  RawGlueDatabaseName:
    Default: txma-raw
    Type: String
    Description: Name for the TxMA Raw Glue database
  StageGlueDatabaseName:
    Default: txma-stage
    Type: String
    Description: Name for the TxMA Stage Glue database
  BuildAccountId:
    Default: 991664831801
    Type: String
    Description: Account number of the build account used to grant it S3 access in other accounts
    AllowedValues:
      - 991664831801
  TestRoleArn:
    Type: String
    Description: The ARN of the role that will used by secure pipelines to run integration tests
    Default: none
    AllowedPattern: (none)|(arn:aws:iam::.*:role/.*)
  RedshiftSecretLength:
    Type: Number
    Description: Length of the redshift password stored in secretsmanager
    Default: 16
  RedshiftSecretExcludeCharacters:
    Type: String
    Description: String of characters to exclude from the redshift password stored in secretsmanager
    Default: '"''@/\'
  CrossAccountDataSyncRoleName:
    Type: String
    Description: Name of the role allowing cross account data sync
    Default: dap-cross-account-data-sync-role
    AllowedValues:
      - dap-cross-account-data-sync-role

Conditions:
  UseCodeSigning: !Not
    - !Equals
      - !Ref CodeSigningConfigArn
      - none
  UsePermissionsBoundary: !Not
    - !Equals
      - !Ref PermissionsBoundary
      - none
  UseTestingContainers: !Not
    - !Equals
      - !Ref TestRoleArn
      - none
  IsTest: !Equals [!Ref Environment, test]
  IsFeature: !Equals [!Ref Environment, feature]
  IsNotFeature: !Not [!Equals [!Ref Environment, feature]]
  IsDev: !Equals [!Ref Environment, dev]
  IsBuild: !Equals [!Ref Environment, build]
  IsIntegration: !Equals [!Ref Environment, integration]
  IsStaging: !Equals [!Ref Environment, staging]
  IsProduction: !Equals [!Ref Environment, production]
  IsProductionPreview: !Equals [!Ref Environment, production-preview]
  IsNotProductionPreview: !Not [!Equals [!Ref Environment, production-preview]]
  IsCrossAccountDataSyncEnvironment: !Or
    - !Condition IsStaging
    - !Condition IsProductionPreview
  UsePlaceholderTxMAQueue: !Or
    - !Condition IsTest
    - !Condition IsFeature
    # todo replace line below with `- !Condition IsDev` when txma queue has been moved from dev to staging
    - !Condition IsStaging
    - !Condition IsBuild
    - !Condition IsProductionPreview
  # is this an environment that uses secure pipelines for deployments (feature and production-preview do direct sam deploys)
  # used to determine if extra policies need to be added to the secure pipelines deploy role in pipeline.yml
  IsSecurePipelinesEnvironment: !And
    - !Condition IsNotFeature
    - !Condition IsNotProductionPreview

Globals:
  Function:
    CodeSigningConfigArn: !If
      - UseCodeSigning
      - !Ref CodeSigningConfigArn
      - !Ref 'AWS::NoValue'
    PermissionsBoundary: !If
      - UsePermissionsBoundary
      - !Ref PermissionsBoundary
      - !Ref 'AWS::NoValue'
    Runtime: nodejs18.x
    Timeout: 30
    CodeUri: dist/
    Environment:
      Variables:
        NODE_OPTIONS: '--enable-source-maps'
