AWSTemplateFormatVersion: 2010-09-09
Description: Data and Analytics Stack
Transform: AWS::Serverless-2016-10-31

Outputs:
  TXMAQueueURL:
    Description: 'TxMA queue URL'
    Value: !If [UsePlaceholderTxMAQueue, !Ref EventConsumerQueue, '']

  TXMABucket:
    Description: 'Name of raw bucket'
    Value: !Ref RawLayerBucket

Parameters:
  Environment:
    Description: Environment type
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - build
      - staging
      - integration
      - production
      - production-preview
  CodeSigningConfigArn:
    Description: ARN of Code Signing Config from deployment pipeline
    Type: String
    Default: none
  PermissionsBoundary:
    Description: ARN of permissions boundary for new roles
    Type: String
    Default: none
  DeliveryStreamName:
    Description: Kinesis Firehose delivery stream name
    Type: String
    Default: dap-txma-delivery-stream
  RawGlueDatabaseName:
    Default: txma-raw
    Type: String
    Description: Name for the TxMA Raw Glue database
  StageGlueDatabaseName:
    Default: txma-stage
    Type: String
    Description: Name for the TxMA Stage Glue database
  BuildAccountId:
    Default: 991664831801
    Type: String
    Description: Account number of the build account used to grant it S3 access in other accounts
    AllowedValues:
      - 991664831801
  TestRoleArn:
    Type: String
    Description: The ARN of the role that will used by secure pipelines to run integration tests
    Default: none
    AllowedPattern: (none)|(arn:aws:iam::.*:role/.*)
  RedshiftSecretLength:
    Type: Number
    Description: Length of the redshift password stored in secretsmanager
    Default: 16
  RedshiftSecretExcludeCharacters:
    Type: String
    Description: String of characters to exclude from the redshift password stored in secretsmanager
    Default: '"''@/\'
  SlackWorkspaceId:
    Description: Workspace ID for GDS Slack
    Type: String
    Default: T8GT9416G

Mappings:
  DAPNotificationsSlackChannelIds:
    dev:
      SlackChannelId: C083A3B482G
    build:
      SlackChannelId: C083A3B482G
    staging:
      SlackChannelId: C083A3B482G
    integration:
      SlackChannelId: C083A3B482G
    production-preview:
      SlackChannelId: C083A3B482G
    production:
      SlackChannelId: C09D8TDHX1T
  EnvironmentConfiguration:
    dev:
      dynatraceSecretArn: arn:aws:secretsmanager:eu-west-2:216552277552:secret:DynatraceNonProductionVariables
    build:
      dynatraceSecretArn: arn:aws:secretsmanager:eu-west-2:216552277552:secret:DynatraceNonProductionVariables
    staging:
      dynatraceSecretArn: arn:aws:secretsmanager:eu-west-2:216552277552:secret:DynatraceNonProductionVariables
    integration:
      dynatraceSecretArn: arn:aws:secretsmanager:eu-west-2:216552277552:secret:DynatraceNonProductionVariables
    production-preview:
      ddynatraceSecretArn: unused
    production:
      dynatraceSecretArn: arn:aws:secretsmanager:eu-west-2:216552277552:secret:DynatraceProductionVariables

Conditions:
  UseCodeSigning: !Not
    - !Equals
      - !Ref CodeSigningConfigArn
      - none
  UsePermissionsBoundary: !Not
    - !Equals
      - !Ref PermissionsBoundary
      - none
  UseTestingContainers: !Not
    - !Equals
      - !Ref TestRoleArn
      - none
  IsDev: !Equals [!Ref Environment, dev]
  IsBuild: !Equals [!Ref Environment, build]
  IsIntegration: !Equals [!Ref Environment, integration]
  IsStaging: !Equals [!Ref Environment, staging]
  IsProduction: !Equals [!Ref Environment, production]
  IsProductionPreview: !Equals [!Ref Environment, production-preview]
  IsDevOrBuild: !Or
    - !Condition IsDev
    - !Condition IsBuild
  IsQuicksightEnvironment: !Or
    - !Condition IsDev
    - !Condition IsProduction
    - !Condition IsProductionPreview
  UsePlaceholderTxMAQueue: !Or
    - !Condition IsDev
    - !Condition IsBuild
    - !Condition IsProductionPreview
  # is this an environment that uses secure pipelines for deployments (production-preview does a direct sam deploy)
  # used to determine if extra policies need to be added to the secure pipelines deploy role in pipeline.yml
  IsSecurePipelinesEnvironment: !Not [!Condition IsProductionPreview]
  IsManualReferenceDataEnvironment: !Or
    - !Condition IsProduction
    - !Condition IsProductionPreview
  IsADMEnvironment: !Or
    - !Condition IsProduction
    - !Condition IsProductionPreview

Globals:
  Function:
    CodeSigningConfigArn: !If
      - UseCodeSigning
      - !Ref CodeSigningConfigArn
      - !Ref 'AWS::NoValue'
    PermissionsBoundary: !If
      - UsePermissionsBoundary
      - !Ref PermissionsBoundary
      - !Ref 'AWS::NoValue'
    Runtime: nodejs22.x
    Timeout: 30
    CodeUri: dist/
    MemorySize: 1024
    Environment:
      Variables:
        NODE_OPTIONS: '--enable-source-maps'
        DT_CONNECTION_AUTH_TOKEN: !If
          - IsSecurePipelinesEnvironment
          - !Sub
            - '{{resolve:secretsmanager:${SecretArn}:SecretString:DT_CONNECTION_AUTH_TOKEN}}'
            - SecretArn: !FindInMap [EnvironmentConfiguration, !Ref Environment, dynatraceSecretArn]
          - !Ref 'AWS::NoValue'
        DT_CONNECTION_BASE_URL: !If
          - IsSecurePipelinesEnvironment
          - !Sub
            - '{{resolve:secretsmanager:${SecretArn}:SecretString:DT_CONNECTION_BASE_URL}}'
            - SecretArn: !FindInMap [EnvironmentConfiguration, !Ref Environment, dynatraceSecretArn]
          - !Ref 'AWS::NoValue'
        DT_CLUSTER_ID: !If
          - IsSecurePipelinesEnvironment
          - !Sub
            - '{{resolve:secretsmanager:${SecretArn}:SecretString:DT_CLUSTER_ID}}'
            - SecretArn: !FindInMap [EnvironmentConfiguration, !Ref Environment, dynatraceSecretArn]
          - !Ref 'AWS::NoValue'
        DT_LOG_COLLECTION_AUTH_TOKEN: !If
          - IsSecurePipelinesEnvironment
          - !Sub
            - '{{resolve:secretsmanager:${SecretArn}:SecretString:DT_LOG_COLLECTION_AUTH_TOKEN}}'
            - SecretArn: !FindInMap [EnvironmentConfiguration, !Ref Environment, dynatraceSecretArn]
          - !Ref 'AWS::NoValue'
        DT_TENANT: !If
          - IsSecurePipelinesEnvironment
          - !Sub
            - '{{resolve:secretsmanager:${SecretArn}:SecretString:DT_TENANT}}'
            - SecretArn: !FindInMap [EnvironmentConfiguration, !Ref Environment, dynatraceSecretArn]
          - !Ref 'AWS::NoValue'
        DT_OPEN_TELEMETRY_ENABLE_INTEGRATION: !If
          - IsSecurePipelinesEnvironment
          - 'true'
          - !Ref 'AWS::NoValue'
    Layers: !If
      - IsSecurePipelinesEnvironment
      - - arn:aws:lambda:eu-west-2:216552277552:layer:Dynatrace_OneAgent_1_313_2_20250404-043044_with_collector_nodejs:1
      - !Ref 'AWS::NoValue'
