import {
  generateTimestamp,
  generateTimestampFormatted,
  generateTimestampInMs,
  generateDateCreatedPartition,
  generateProcessedDt,
  generateProcessedTime,
} from '../../helpers/utils/utils';
import {
  constructDCMAWAsyncBiometricTokenIssuedDAPEvent,
  constructDCMAWAsyncBiometricTokenIssuedExpectedRawLayerRow,
  constructDCMAWAsyncBiometricTokenIssuedExpectedStageLayerRow,
  constructDCMAWAsyncBiometricTokenIssuedExpectedStageLayerKeyValues,
  constructDCMAWAsyncBiometricTokenIssuedExpectedConformedData,
} from './dcmaw-async-biometric-token-issued-dap-event';
import {
  constructDCMAWCriStartTestEvent1,
  constructDCMAWCriStartTestEvent1ExpectedConformedData,
  constructDCMAWCriStartTestEvent1ExpectedRawLayerRow,
  constructDCMAWCriStartTestEvent1ExpectedStageLayerKeyValues,
  constructDCMAWCriStartTestEvent1ExpectedStageLayerRow,
} from './test-event-1-dcmaw-cri-start-dap';
import {
  constructDCMAWCriStartTestEvent2,
  constructDCMAWCriStartTestEvent2ExpectedRawLayerRow,
  constructDCMAWCriStartTestEvent2ExpectedStageLayerKeyValues,
  constructDCMAWCriStartTestEvent2ExpectedStageLayerRow,
  constructDCMAWCriStartTestEvent2ExpectedConformedData,
} from './test-event-2-dcmaw-cri-start-dap';
import {
  constructDCMAWCriStartTestEvent3,
  constructDCMAWCriStartTestEvent3ExpectedRawLayerRow,
  constructDCMAWCriStartTestEvent3ExpectedStageLayerKeyValues,
  constructDCMAWCriStartTestEvent3ExpectedStageLayerRow,
  constructDCMAWCriStartTestEvent3ExpectedConformedData,
} from './test-event-3-dcmaw-cri-start-dap';
import {
  constructDCMAWCriStartTestEvent4,
  constructDCMAWCriStartTestEvent4ExpectedRawLayerRow,
  constructDCMAWCriStartTestEvent4ExpectedStageLayerKeyValues,
  constructDCMAWCriStartTestEvent4ExpectedStageLayerRow,
  constructDCMAWCriStartTestEvent4ExpectedConformedData,
} from './test-event-4-dcmaw-cri-start-dap';
import {
  constructIPVAsyncCriVcConsumedTestEvent5,
  constructIPVAsyncCriVcConsumedTestEvent5ExpectedRawLayerRow,
  constructIPVAsyncCriVcConsumedTestEvent5ExpectedStageLayerKeyValues,
  constructIPVAsyncCriVcConsumedTestEvent5ExpectedStageLayerRow,
  constructIPVAsyncCriVcConsumedTestEvent5ExpectedConformedData,
} from './test-event-5-ipv-async-cri-vc-consumed-dap';
import {
  constructAuthMfaMethodAlternativeRequestedTestEvent6,
  constructAuthMfaMethodAlternativeRequestedTestEvent6ExpectedRawLayerRow,
  constructAuthMfaMethodAlternativeRequestedTestEvent6ExpectedStageLayerKeyValues,
  constructAuthMfaMethodAlternativeRequestedTestEvent6ExpectedStageLayerRow,
  constructAuthMfaMethodAlternativeRequestedTestEvent6ExpectedConformedData,
} from './test-event-6-auth-mfa-method-alternative-requested-dap';
import {
  constructAuthMfaMethodAddFailedTestEvent7,
  constructAuthMfaMethodAddFailedTestEvent7ExpectedRawLayerRow,
  constructAuthMfaMethodAddFailedTestEvent7ExpectedStageLayerKeyValues,
  constructAuthMfaMethodAddFailedTestEvent7ExpectedStageLayerRow,
  constructAuthMfaMethodAddFailedTestEvent7ExpectedConformedData,
} from './test-event-7-auth-mfa-method-add-failed-dap';
import {
  constructAuthEmailFraudCheckResponseReceivedTestEvent8,
  constructAuthEmailFraudCheckResponseReceivedTestEvent8ExpectedRawLayerRow,
  constructAuthEmailFraudCheckResponseReceivedTestEvent8ExpectedStageLayerKeyValues,
  constructAuthEmailFraudCheckResponseReceivedTestEvent8ExpectedStageLayerRow,
  constructAuthEmailFraudCheckResponseReceivedTestEvent8ExpectedConformedData,
} from './test-event-8-auth-email-fraud-check-response-received-dap';
import {
  constructIpvSpotResponseApprovedTestEvent9,
  constructIpvSpotResponseApprovedTestEvent9ExpectedRawLayerRow,
  constructIpvSpotResponseApprovedTestEvent9ExpectedStageLayerKeyValues,
  constructIpvSpotResponseApprovedTestEvent9ExpectedStageLayerRow,
  constructIpvSpotResponseApprovedTestEvent9ExpectedConformedData,
} from './test-event-9-ipv-spot-response-approved-dap';
import {
  constructAuthAuthorisationInitiatedTestEvent10,
  constructAuthAuthorisationInitiatedTestEvent10ExpectedRawLayerRow,
  constructAuthAuthorisationInitiatedTestEvent10ExpectedStageLayerKeyValues,
  constructAuthAuthorisationInitiatedTestEvent10ExpectedStageLayerRow,
  constructAuthAuthorisationInitiatedTestEvent10ExpectedConformedData,
} from './test-event-10-auth-authorisation-initiated-dap';
import {
  constructAuthMfaMethodAddStartedTestEvent11,
  constructAuthMfaMethodAddStartedTestEvent11ExpectedRawLayerRow,
  constructAuthMfaMethodAddStartedTestEvent11ExpectedStageLayerKeyValues,
  constructAuthMfaMethodAddStartedTestEvent11ExpectedStageLayerRow,
  constructAuthMfaMethodAddStartedTestEvent11ExpectedConformedData,
} from './test-event-11-auth-mfa-method-add-started-dap';
import {
  constructAuthMfaMethodAddStartedTestEvent12,
  constructAuthMfaMethodAddStartedTestEvent12ExpectedRawLayerRow,
  constructAuthMfaMethodAddStartedTestEvent12ExpectedStageLayerKeyValues,
  constructAuthMfaMethodAddStartedTestEvent12ExpectedStageLayerRow,
  constructAuthMfaMethodAddStartedTestEvent12ExpectedConformedData,
} from './test-event-12-auth-mfa-method-add-started-dap';

const timestamp = generateTimestamp();
const timestamp_formatted = generateTimestampFormatted();
const event_timestamp_ms = generateTimestampInMs();
const event_timestamp_ms_formatted = generateTimestampFormatted();
const datecreated = generateDateCreatedPartition();
const now = new Date();
const year = now.getFullYear();
const month = now.getMonth() + 1;
const day = now.getDate();
const date = `${year}-${String(month).padStart(2, '0')}-${String(day).padStart(2, '0')}`;
const processed_dt = generateProcessedDt();
const processed_time = generateProcessedTime();

export const happyPathEventList = [
  {
    testEventNumber: 0,
    auditEvent: constructDCMAWAsyncBiometricTokenIssuedDAPEvent(
      timestamp,
      timestamp_formatted,
      event_timestamp_ms,
      event_timestamp_ms_formatted,
      'testClientId',
      'testUserId',
      'testJourneyId',
    ),
    rawLayerEvent: constructDCMAWAsyncBiometricTokenIssuedExpectedRawLayerRow(
      timestamp,
      timestamp_formatted,
      event_timestamp_ms,
      event_timestamp_ms_formatted,
      'testClientId',
      'testUserId',
      'testJourneyId',
      datecreated,
    ),
    stageLayerEvent: constructDCMAWAsyncBiometricTokenIssuedExpectedStageLayerRow(
      timestamp,
      timestamp_formatted,
      event_timestamp_ms,
      event_timestamp_ms_formatted,
      'testClientId',
      'testUserId',
      'testJourneyId',
      year,
      month,
      day,
      processed_dt,
      processed_time,
    ),
    stageLayerKeyValues: constructDCMAWAsyncBiometricTokenIssuedExpectedStageLayerKeyValues(
      processed_dt,
      processed_time,
    ),
    conformedEvent: constructDCMAWAsyncBiometricTokenIssuedExpectedConformedData('testUserId', 'testJourneyId', date),
  },
  {
    testEventNumber: 1,
    auditEvent: constructDCMAWCriStartTestEvent1(timestamp, timestamp_formatted),
    rawLayerEvent: constructDCMAWCriStartTestEvent1ExpectedRawLayerRow(timestamp, timestamp_formatted, datecreated),
    stageLayerEvent: constructDCMAWCriStartTestEvent1ExpectedStageLayerRow(
      timestamp,
      timestamp_formatted,
      year,
      month,
      day,
      processed_dt,
      processed_time,
    ),
    stageLayerKeyValues: constructDCMAWCriStartTestEvent1ExpectedStageLayerKeyValues(),
    conformedEvent: constructDCMAWCriStartTestEvent1ExpectedConformedData(date),
  },
  {
    testEventNumber: 2,
    auditEvent: constructDCMAWCriStartTestEvent2(
      timestamp,
      timestamp_formatted,
      event_timestamp_ms,
      event_timestamp_ms_formatted,
    ),
    rawLayerEvent: constructDCMAWCriStartTestEvent2ExpectedRawLayerRow(
      timestamp,
      timestamp_formatted,
      event_timestamp_ms,
      event_timestamp_ms_formatted,
      datecreated,
    ),
    stageLayerEvent: constructDCMAWCriStartTestEvent2ExpectedStageLayerRow(
      timestamp,
      timestamp_formatted,
      event_timestamp_ms,
      event_timestamp_ms_formatted,
      year,
      month,
      day,
      processed_dt,
      processed_time,
    ),
    stageLayerKeyValues: constructDCMAWCriStartTestEvent2ExpectedStageLayerKeyValues(),
    conformedEvent: constructDCMAWCriStartTestEvent2ExpectedConformedData(date),
  },
  {
    testEventNumber: 3,
    auditEvent: constructDCMAWCriStartTestEvent3(
      timestamp,
      timestamp_formatted,
      event_timestamp_ms,
      event_timestamp_ms_formatted,
      'testClientId',
    ),
    rawLayerEvent: constructDCMAWCriStartTestEvent3ExpectedRawLayerRow(
      timestamp,
      timestamp_formatted,
      event_timestamp_ms,
      event_timestamp_ms_formatted,
      'testClientId',
      datecreated,
    ),
    stageLayerEvent: constructDCMAWCriStartTestEvent3ExpectedStageLayerRow(
      timestamp,
      timestamp_formatted,
      event_timestamp_ms,
      event_timestamp_ms_formatted,
      'testClientId',
      year,
      month,
      day,
      processed_dt,
      processed_time,
    ),
    stageLayerKeyValues: constructDCMAWCriStartTestEvent3ExpectedStageLayerKeyValues(),
    conformedEvent: constructDCMAWCriStartTestEvent3ExpectedConformedData(date),
  },
  {
    testEventNumber: 4,
    auditEvent: constructDCMAWCriStartTestEvent4(
      timestamp,
      timestamp_formatted,
      event_timestamp_ms,
      event_timestamp_ms_formatted,
      'testClientId',
      'testJourneyId',
    ),
    rawLayerEvent: constructDCMAWCriStartTestEvent4ExpectedRawLayerRow(
      timestamp,
      timestamp_formatted,
      event_timestamp_ms,
      event_timestamp_ms_formatted,
      'testClientId',
      'testJourneyId',
      datecreated,
    ),
    stageLayerEvent: constructDCMAWCriStartTestEvent4ExpectedStageLayerRow(
      timestamp,
      timestamp_formatted,
      event_timestamp_ms,
      event_timestamp_ms_formatted,
      'testClientId',
      'testJourneyId',
      year,
      month,
      day,
      processed_dt,
      processed_time,
    ),
    stageLayerKeyValues: constructDCMAWCriStartTestEvent4ExpectedStageLayerKeyValues(),
    conformedEvent: constructDCMAWCriStartTestEvent4ExpectedConformedData('testJourneyId', date),
  },
  {
    testEventNumber: 5,
    auditEvent: constructIPVAsyncCriVcConsumedTestEvent5(
      timestamp,
      timestamp_formatted,
      event_timestamp_ms,
      event_timestamp_ms_formatted,
      'testUserId',
      'testJourneyId',
    ),
    rawLayerEvent: constructIPVAsyncCriVcConsumedTestEvent5ExpectedRawLayerRow(
      timestamp,
      timestamp_formatted,
      event_timestamp_ms,
      event_timestamp_ms_formatted,
      'testUserId',
      'testJourneyId',
      datecreated,
    ),
    stageLayerEvent: constructIPVAsyncCriVcConsumedTestEvent5ExpectedStageLayerRow(
      timestamp,
      timestamp_formatted,
      event_timestamp_ms,
      event_timestamp_ms_formatted,
      'testUserId',
      'testJourneyId',
      year,
      month,
      day,
      processed_dt,
      processed_time,
    ),
    stageLayerKeyValues: constructIPVAsyncCriVcConsumedTestEvent5ExpectedStageLayerKeyValues(),
    conformedEvent: constructIPVAsyncCriVcConsumedTestEvent5ExpectedConformedData('testJourneyId', 'testUserId', date),
  },
  {
    testEventNumber: 6,
    auditEvent: constructAuthMfaMethodAlternativeRequestedTestEvent6(
      timestamp,
      timestamp_formatted,
      event_timestamp_ms,
      event_timestamp_ms_formatted,
      'testClientId',
      'testUserId',
      'testJourneyId',
    ),
    rawLayerEvent: constructAuthMfaMethodAlternativeRequestedTestEvent6ExpectedRawLayerRow(
      timestamp,
      timestamp_formatted,
      event_timestamp_ms,
      event_timestamp_ms_formatted,
      'testClientId',
      'testUserId',
      'testJourneyId',
      datecreated,
    ),
    stageLayerEvent: constructAuthMfaMethodAlternativeRequestedTestEvent6ExpectedStageLayerRow(
      timestamp,
      timestamp_formatted,
      event_timestamp_ms,
      event_timestamp_ms_formatted,
      'testClientId',
      'testUserId',
      'testJourneyId',
      year,
      month,
      day,
      processed_dt,
      processed_time,
    ),
    stageLayerKeyValues: constructAuthMfaMethodAlternativeRequestedTestEvent6ExpectedStageLayerKeyValues(),
    conformedEvent: constructAuthMfaMethodAlternativeRequestedTestEvent6ExpectedConformedData(
      'testJourneyId',
      'testUserId',
      date,
    ),
  },
  {
    testEventNumber: 7,
    auditEvent: constructAuthMfaMethodAddFailedTestEvent7(
      timestamp,
      timestamp_formatted,
      event_timestamp_ms,
      event_timestamp_ms_formatted,
    ),
    rawLayerEvent: constructAuthMfaMethodAddFailedTestEvent7ExpectedRawLayerRow(
      timestamp,
      timestamp_formatted,
      event_timestamp_ms,
      event_timestamp_ms_formatted,
      datecreated,
    ),
    stageLayerEvent: constructAuthMfaMethodAddFailedTestEvent7ExpectedStageLayerRow(
      timestamp,
      timestamp_formatted,
      event_timestamp_ms,
      event_timestamp_ms_formatted,
      year,
      month,
      day,
      processed_dt,
      processed_time,
    ),
    stageLayerKeyValues: constructAuthMfaMethodAddFailedTestEvent7ExpectedStageLayerKeyValues(
      processed_dt,
      processed_time,
    ),
    conformedEvent: constructAuthMfaMethodAddFailedTestEvent7ExpectedConformedData(date),
  },
  {
    testEventNumber: 8,
    auditEvent: constructAuthEmailFraudCheckResponseReceivedTestEvent8(
      timestamp,
      timestamp_formatted,
      event_timestamp_ms,
      event_timestamp_ms_formatted,
    ),
    rawLayerEvent: constructAuthEmailFraudCheckResponseReceivedTestEvent8ExpectedRawLayerRow(
      timestamp,
      timestamp_formatted,
      event_timestamp_ms,
      event_timestamp_ms_formatted,
      datecreated,
    ),
    stageLayerEvent: constructAuthEmailFraudCheckResponseReceivedTestEvent8ExpectedStageLayerRow(
      timestamp,
      timestamp_formatted,
      event_timestamp_ms,
      event_timestamp_ms_formatted,
      year,
      month,
      day,
      processed_dt,
      processed_time,
    ),
    stageLayerKeyValues: constructAuthEmailFraudCheckResponseReceivedTestEvent8ExpectedStageLayerKeyValues(
      processed_dt,
      processed_time,
    ),
    conformedEvent: constructAuthEmailFraudCheckResponseReceivedTestEvent8ExpectedConformedData(date),
  },
  {
    testEventNumber: 9,
    auditEvent: constructIpvSpotResponseApprovedTestEvent9(
      timestamp,
      timestamp_formatted,
      event_timestamp_ms,
      event_timestamp_ms_formatted,
    ),
    rawLayerEvent: constructIpvSpotResponseApprovedTestEvent9ExpectedRawLayerRow(
      timestamp,
      timestamp_formatted,
      event_timestamp_ms,
      event_timestamp_ms_formatted,
      datecreated,
    ),
    stageLayerEvent: constructIpvSpotResponseApprovedTestEvent9ExpectedStageLayerRow(
      timestamp,
      timestamp_formatted,
      event_timestamp_ms,
      event_timestamp_ms_formatted,
      year,
      month,
      day,
      processed_dt,
      processed_time,
    ),
    stageLayerKeyValues: constructIpvSpotResponseApprovedTestEvent9ExpectedStageLayerKeyValues(
      processed_dt,
      processed_time,
    ),
    conformedEvent: constructIpvSpotResponseApprovedTestEvent9ExpectedConformedData(date),
  },
  {
    testEventNumber: 10,
    auditEvent: constructAuthAuthorisationInitiatedTestEvent10(
      timestamp,
      timestamp_formatted,
      event_timestamp_ms,
      event_timestamp_ms_formatted,
    ),
    rawLayerEvent: constructAuthAuthorisationInitiatedTestEvent10ExpectedRawLayerRow(
      timestamp,
      timestamp_formatted,
      event_timestamp_ms,
      event_timestamp_ms_formatted,
      datecreated,
    ),
    stageLayerEvent: constructAuthAuthorisationInitiatedTestEvent10ExpectedStageLayerRow(
      timestamp,
      timestamp_formatted,
      event_timestamp_ms,
      event_timestamp_ms_formatted,
      year,
      month,
      day,
      processed_dt,
      processed_time,
    ),
    stageLayerKeyValues: constructAuthAuthorisationInitiatedTestEvent10ExpectedStageLayerKeyValues(
      processed_dt,
      processed_time,
    ),
    conformedEvent: constructAuthAuthorisationInitiatedTestEvent10ExpectedConformedData(date),
  },
  {
    testEventNumber: 11,
    auditEvent: constructAuthMfaMethodAddStartedTestEvent11(
      timestamp,
      timestamp_formatted,
      event_timestamp_ms,
      event_timestamp_ms_formatted,
    ),
    rawLayerEvent: constructAuthMfaMethodAddStartedTestEvent11ExpectedRawLayerRow(
      timestamp,
      timestamp_formatted,
      event_timestamp_ms,
      event_timestamp_ms_formatted,
      datecreated,
    ),
    stageLayerEvent: constructAuthMfaMethodAddStartedTestEvent11ExpectedStageLayerRow(
      timestamp,
      timestamp_formatted,
      event_timestamp_ms,
      event_timestamp_ms_formatted,
      year,
      month,
      day,
      processed_dt,
      processed_time,
    ),
    stageLayerKeyValues: constructAuthMfaMethodAddStartedTestEvent11ExpectedStageLayerKeyValues(),
    conformedEvent: constructAuthMfaMethodAddStartedTestEvent11ExpectedConformedData(date),
  },
  {
    testEventNumber: 12,
    auditEvent: constructAuthMfaMethodAddStartedTestEvent12(
      timestamp,
      timestamp_formatted,
      event_timestamp_ms,
      event_timestamp_ms_formatted,
    ),
    rawLayerEvent: constructAuthMfaMethodAddStartedTestEvent12ExpectedRawLayerRow(
      timestamp,
      timestamp_formatted,
      event_timestamp_ms,
      event_timestamp_ms_formatted,
      datecreated,
    ),
    stageLayerEvent: constructAuthMfaMethodAddStartedTestEvent12ExpectedStageLayerRow(
      timestamp,
      timestamp_formatted,
      event_timestamp_ms,
      event_timestamp_ms_formatted,
      year,
      month,
      day,
      processed_dt,
      processed_time,
    ),
    stageLayerKeyValues: constructAuthMfaMethodAddStartedTestEvent12ExpectedStageLayerKeyValues(
      processed_dt,
      processed_time,
    ),
    conformedEvent: constructAuthMfaMethodAddStartedTestEvent12ExpectedConformedData(date),
  },
];
