/**
 * Central registry of DAP lambda error codes.
 *
 * Codes are allocated in the `DAP0xx` range. Codes `DAP001`-`DAP003` are reserved by the
 * `copy-raw-to-stage-code` handler (see its local `error-codes.ts`). New codes MUST be unique
 * and MUST NOT be reused once retired.
 */
export const ERROR_CODES = {
  RAW_TO_STAGE_FAILED: 'DAP101',
  RAW_TO_STAGE_COPY_FAILED: 'DAP102',
  MISSING_EVENT_DETAIL: 'DAP1601',
  SEND_METADATA_FAILED: 'DAP201',
  GET_METADATA_FAILED: 'DAP301',
  METADATA_NOT_FOUND: 'DAP302',
  VALIDATE_EXECUTION_FAILED: 'DAP401',
  DUPLICATE_EXECUTION_DETECTED: 'DAP402',
  GET_STATEMENT_FAILED: 'DAP501',
  GET_CONFIG_FAILED: 'DAP502',
  POST_AUTHENTICATION_FAILED: 'DAP601',
  QUICKSIGHT_EMBED_URL_FAILED: 'DAP701',
  QUICKSIGHT_EXPORT_FAILED: 'DAP801',
  QUICKSIGHT_EXPORT_JOB_INCOMPLETE: 'DAP802',
  QUICKSIGHT_EXPORT_JOB_STATUS_FAILED: 'DAP803',
  QUICKSIGHT_EXPORT_UPLOAD_FAILED: 'DAP804',
  QUICKSIGHT_IMPORT_FAILED: 'DAP805',
  QUICKSIGHT_IMPORT_JOB_INCOMPLETE: 'DAP806',
  QUICKSIGHT_IMPORT_JOB_STATUS_FAILED: 'DAP807',
  FLYWAY_COMMAND_FAILED: 'DAP901',
  REDSHIFT_ERROR_NOTIFICATION_FAILED: 'DAP1001',
  REDSHIFT_STORED_PROCEDURE_FAILURE: 'DAP1002',
  ROTATE_SECRET_FAILED: 'DAP1101',
  CREATE_SNAPSHOT_FAILED: 'DAP1201',
  FIREHOSE_DELIVERY_FAILED: 'DAP1301',
  INVALID_AUDIT_EVENT: 'DAP1302',
  RECORD_PROCESSING_FAILED: 'DAP1303',
  DLQ_EVENT_PROCESSING_FAILED: 'DAP1401',
  TEST_SUPPORT_FAILED: 'DAP1501',
  TEST_SUPPORT_QUERY_FAILED: 'DAP1502',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
