export type SharedTestEnvName =
  | 'AWS_REGION'
  | 'STACK_NAME'
  | 'ATHENA_WORKGROUP'
  | 'RAW_LAYER_DATABASE'
  | 'RAW_LAYER_BUCKET'
  | 'STAGE_LAYER_DATABASE'
  | 'RAW_TO_STAGE_STEP_FUNCTION'
  | 'STAGE_TO_CONFORM_STEP_FUNCTION'
  | 'REDSHIFT_WORKGROUP_NAME'
  | 'REDSHIFT_SECRET_ARN';
