ARG ALPINE_VERSION=3.16

FROM node:16-alpine${ALPINE_VERSION} AS run-tests
WORKDIR /test-app

COPY package.json package-lock.json tsconfig.json jest.e2e.config.ts ./
COPY integration_tests ./integration_tests
COPY src/handlers/int-test-support/ ./src/handlers/int-test-support/
COPY src/shared/ ./src/shared/

RUN npm ci

WORKDIR /test-app/integration_tests

RUN mv ./run-e2e-tests.sh /run-tests.sh
RUN chmod +x /run-tests.sh

ENV TEST_VIA_LAMBDA=true

ENTRYPOINT ["/run-e2e-tests.sh"]



