TfstateBucket:
  Type: AWS::S3::Bucket
  Properties:
    BucketName: !Sub di-txma-dap-${Environment}-tfstate
    PublicAccessBlockConfiguration:
      BlockPublicAcls: true
      BlockPublicPolicy: true
      IgnorePublicAcls: true
      RestrictPublicBuckets: true
