#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx lint-staged

git diff --cached --name-only | if grep --quiet 'iac/'; then
  echo "Running sam validate and checkov checks on IaC code"
  npm run iac:lint
  npm run iac:scan
fi
