AWSTemplateFormatVersion: 2010-09-09
Description: Quicksight Access Stack
Transform: AWS::Serverless-2016-10-31

Parameters:
  Environment:
    Description: Environment type
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - build
      - staging
      - integration
      - production
      - production-preview
  CodeSigningConfigArn:
    Description: ARN of Code Signing Config from deployment pipeline
    Type: String
    Default: none
  PermissionsBoundary:
    Description: ARN of permissions boundary for new roles
    Type: String
    Default: none
  SlackWorkspaceId:
    Description: Workspace ID for GDS Slack
    Type: String
    Default: T8GT9416G
  DAPAlertsChannelId:
    Description: Channel ID for di_dap_alerts where we will send alerts that concern both DAP devs and analysts
    Type: String
    Default: C069TS28PGE
Mappings:
  DKIMRecordMap:
    dev:
      Name1: zs2dfseiiy7xvwdswfyxccyvtzqdytv3._domainkey.dap.dev.account.gov.uk
      Name2: 4sg43w2i5nt4gbemquvgfagfldax6g4u._domainkey.dap.dev.account.gov.uk
      Name3: ms7qqbyvkfjeoxhzjdsn3fyhqg6t5kmx._domainkey.dap.dev.account.gov.uk
      Value1: zs2dfseiiy7xvwdswfyxccyvtzqdytv3.dkim.amazonses.com
      Value2: 4sg43w2i5nt4gbemquvgfagfldax6g4u.dkim.amazonses.com
      Value3: ms7qqbyvkfjeoxhzjdsn3fyhqg6t5kmx.dkim.amazonses.com
    production:
      Name1: o5b7hzt6in42sxz4fubsutlp4v72myre._domainkey.dap.account.gov.uk
      Name2: 2oycgq2ysih3clrmbel4u2xa6w52k26k._domainkey.dap.account.gov.uk
      Name3: dur4gqp5mqm63drleftnpvdjkjvofepy._domainkey.dap.account.gov.uk
      Value1: o5b7hzt6in42sxz4fubsutlp4v72myre.dkim.amazonses.com
      Value2: 2oycgq2ysih3clrmbel4u2xa6w52k26k.dkim.amazonses.com
      Value3: dur4gqp5mqm63drleftnpvdjkjvofepy.dkim.amazonses.com
  EnvironmentConfiguration:
    dev:
      dynatraceSecretArn: arn:aws:secretsmanager:eu-west-2:216552277552:secret:DynatraceNonProductionVariables
    build:
      dynatraceSecretArn: arn:aws:secretsmanager:eu-west-2:216552277552:secret:DynatraceNonProductionVariables
    staging:
      dynatraceSecretArn: arn:aws:secretsmanager:eu-west-2:216552277552:secret:DynatraceNonProductionVariables
    integration:
      dynatraceSecretArn: arn:aws:secretsmanager:eu-west-2:216552277552:secret:DynatraceNonProductionVariables
    production-preview:
      ddynatraceSecretArn: unused
    production:
      dynatraceSecretArn: arn:aws:secretsmanager:eu-west-2:216552277552:secret:DynatraceProductionVariables

Conditions:
  UseCodeSigning: !Not
    - !Equals
      - !Ref CodeSigningConfigArn
      - none
  UsePermissionsBoundary: !Not
    - !Equals
      - !Ref PermissionsBoundary
      - none
  IsDev: !Equals [!Ref Environment, dev]
  IsProduction: !Equals [!Ref Environment, production]
  IsProductionPreview: !Equals [!Ref Environment, production-preview]
  IsNotProductionPreview: !Not [!Equals [!Ref Environment, production-preview]]
  IsBuild: !Equals [!Ref Environment, build]
  IsIntegration: !Equals [!Ref Environment, integration]
  IsStaging: !Equals [!Ref Environment, staging]
  IsSecurePipelinesEnvironment: !Not [!Condition IsProductionPreview]
  IsQuicksightEnvironment: !Or
    - !Condition IsDev
    - !Condition IsProduction
    - !Condition IsProductionPreview
  # only dev and prod have the configuration (SES, Route53, etc) for sending Cognito emails via SES
  IsDevOrProd: !Or
    - !Condition IsDev
    - !Condition IsProduction
  # is this a quicksight environment that uses secure pipelines for deployments (production-preview does a direct sam deploy)
  # used to determine if extra policies need to be added to the secure pipelines deploy role in pipeline.yml
  IsQuicksightEnvironmentAndIsSecurePipelinesEnvironment:
    Fn::And:
      - Condition: IsQuicksightEnvironment
      - Condition: IsNotProductionPreview

Globals:
  Function:
    CodeSigningConfigArn: !If
      - UseCodeSigning
      - !Ref CodeSigningConfigArn
      - !Ref 'AWS::NoValue'
    PermissionsBoundary: !If
      - UsePermissionsBoundary
      - !Ref PermissionsBoundary
      - !Ref 'AWS::NoValue'
    Runtime: nodejs22.x
    Timeout: 30
    CodeUri: dist/
    Environment:
      Variables:
        NODE_OPTIONS: '--enable-source-maps'
        DT_CONNECTION_AUTH_TOKEN: !If
          - IsSecurePipelinesEnvironment
          - !Sub
            - '{{resolve:secretsmanager:${SecretArn}:SecretString:DT_CONNECTION_AUTH_TOKEN}}'
            - SecretArn: !FindInMap [EnvironmentConfiguration, !Ref Environment, dynatraceSecretArn]
          - !Ref 'AWS::NoValue'
        DT_CONNECTION_BASE_URL: !If
          - IsSecurePipelinesEnvironment
          - !Sub
            - '{{resolve:secretsmanager:${SecretArn}:SecretString:DT_CONNECTION_BASE_URL}}'
            - SecretArn: !FindInMap [EnvironmentConfiguration, !Ref Environment, dynatraceSecretArn]
          - !Ref 'AWS::NoValue'
        DT_CLUSTER_ID: !If
          - IsSecurePipelinesEnvironment
          - !Sub
            - '{{resolve:secretsmanager:${SecretArn}:SecretString:DT_CLUSTER_ID}}'
            - SecretArn: !FindInMap [EnvironmentConfiguration, !Ref Environment, dynatraceSecretArn]
          - !Ref 'AWS::NoValue'
        DT_LOG_COLLECTION_AUTH_TOKEN: !If
          - IsSecurePipelinesEnvironment
          - !Sub
            - '{{resolve:secretsmanager:${SecretArn}:SecretString:DT_LOG_COLLECTION_AUTH_TOKEN}}'
            - SecretArn: !FindInMap [EnvironmentConfiguration, !Ref Environment, dynatraceSecretArn]
          - !Ref 'AWS::NoValue'
        DT_TENANT: !If
          - IsSecurePipelinesEnvironment
          - !Sub
            - '{{resolve:secretsmanager:${SecretArn}:SecretString:DT_TENANT}}'
            - SecretArn: !FindInMap [EnvironmentConfiguration, !Ref Environment, dynatraceSecretArn]
          - !Ref 'AWS::NoValue'
        DT_OPEN_TELEMETRY_ENABLE_INTEGRATION: !If
          - IsSecurePipelinesEnvironment
          - 'true'
          - !Ref 'AWS::NoValue'
    Layers: !If
      - IsSecurePipelinesEnvironment
      - - arn:aws:lambda:eu-west-2:216552277552:layer:Dynatrace_OneAgent_1_313_2_20250404-043044_with_collector_nodejs:1
      - !Ref 'AWS::NoValue'
