name: ✳️ Test and validate iac and lambdas

on:
  pull_request:
  workflow_call:
  workflow_dispatch:

jobs:
  test-and-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v5
      - name: Node setup
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24
          cache: npm
      - name: Install node packages
        run: npm ci

      # js and ts
      - name: JS/TS linting and formatting
        run: npm run lint:check
      - name: Run lambda tests
        run: npm run test
      # iac
      - name: IaC formatting checks
        run: npm run iac:format:check
      - name: Script formatting checks
        run: npm run scripts:format:check
      - name: SAM setup
        uses: aws-actions/setup-sam@89ddb14d60e682855e3fea4be85b3c56485de310 # v2
        with:
          use-installer: true
          version: 1.134.0
      - name: IaC linting checks
        run: npm run iac:lint
      - name: Checkov actions scan
        uses: bridgecrewio/checkov-action@9b70310bcd306d11740313070b940167d6b23085 # v12
        with:
          config_file: .checkov.ci.yml
          directory: iac-dist
          quiet: true
          baseline: .checkov.baseline

      # scripts
      - name: Script formatting checks
        run: npm run scripts:format:check

  build-etl-job:
    # These permissions are needed to interact with GitHub's OIDC Token endpoint (enabling the aws-actions/configure-aws-credentials action)
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v5
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: '3.11'
      - name: Build release distributions
        run: scripts/build-and-deploy-etl.sh
